import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import { auth, db, handleFirestoreError, OperationType } from '../firebase';
import { doc, onSnapshot, updateDoc, getDoc, setDoc } from 'firebase/firestore';
import { onAuthStateChanged } from 'firebase/auth';

export type LanguageCode = 'en' | 'pt-BR' | 'fr' | 'es' | 'de' | 'hi' | 'ru' | 'ja' | 'zh' | 'ko' | 'th';

interface Language {
  code: LanguageCode;
  name: string;
  flag: string;
  currency: string;
  locale: string;
  bills: number[];
  coins: number[];
}

export const languages: Language[] = [
  { 
    code: 'en', 
    name: 'English', 
    flag: '🇺🇸', 
    currency: 'USD', 
    locale: 'en-US',
    bills: [100, 50, 20, 10, 5, 2, 1],
    coins: [1.00, 0.50, 0.25, 0.10, 0.05, 0.01]
  },
  { 
    code: 'pt-BR', 
    name: 'Português (Brasil)', 
    flag: '🇧🇷', 
    currency: 'BRL', 
    locale: 'pt-BR',
    bills: [200, 100, 50, 20, 10, 5, 2],
    coins: [1.00, 0.50, 0.25, 0.10, 0.05]
  },
  { 
    code: 'fr', 
    name: 'Français', 
    flag: '🇫🇷', 
    currency: 'EUR', 
    locale: 'fr-FR',
    bills: [500, 200, 100, 50, 20, 10, 5],
    coins: [2.00, 1.00, 0.50, 0.20, 0.10, 0.05, 0.02, 0.01]
  },
  { 
    code: 'es', 
    name: 'Español', 
    flag: '🇪🇸', 
    currency: 'EUR', 
    locale: 'es-ES',
    bills: [500, 200, 100, 50, 20, 10, 5],
    coins: [2.00, 1.00, 0.50, 0.20, 0.10, 0.05, 0.02, 0.01]
  },
  { 
    code: 'de', 
    name: 'Deutsch', 
    flag: '🇩🇪', 
    currency: 'EUR', 
    locale: 'de-DE',
    bills: [500, 200, 100, 50, 20, 10, 5],
    coins: [2.00, 1.00, 0.50, 0.20, 0.10, 0.05, 0.02, 0.01]
  },
  { 
    code: 'hi', 
    name: 'हिन्दी', 
    flag: '🇮🇳', 
    currency: 'INR', 
    locale: 'hi-IN',
    bills: [500, 200, 100, 50, 20, 10],
    coins: [20, 10, 5, 2, 1]
  },
  { 
    code: 'ru', 
    name: 'Русский', 
    flag: '🇷🇺', 
    currency: 'RUB', 
    locale: 'ru-RU',
    bills: [5000, 2000, 1000, 500, 200, 100, 50, 10, 5],
    coins: [10, 5, 2,  1, 0.50, 0.10, 0.05, 0.01]
  },
  { 
    code: 'ja', 
    name: '日本語', 
    flag: '🇯🇵', 
    currency: 'JPY', 
    locale: 'ja-JP',
    bills: [10000, 5000, 2000, 1000],
    coins: [500, 100, 50, 10, 5, 1]
  },
  { 
    code: 'zh', 
    name: '中文', 
    flag: '🇨🇳', 
    currency: 'CNY', 
    locale: 'zh-CN',
    bills: [100, 50, 20, 10, 5, 1],
    coins: [1, 0.5, 0.1, 0.05, 0.02, 0.01]
  },
  { 
    code: 'ko', 
    name: '한국어', 
    flag: '🇰🇷', 
    currency: 'KRW', 
    locale: 'ko-KR',
    bills: [50000, 10000, 5000, 1000],
    coins: [500, 100, 50, 10]
  },
  { 
    code: 'th', 
    name: 'ไทย', 
    flag: '🇹🇭', 
    currency: 'THB', 
    locale: 'th-TH',
    bills: [1000, 500, 100, 50, 20],
    coins: [10, 5, 2, 1, 0.50, 0.25]
  },
];

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    entries: 'Entries',
    history: 'History',
    profile: 'Profile',
    totalSales: 'Total sales',
    monthlyGoal: 'Monthly goal',
    recentSales: 'Recent sales',
    newSale: 'New sale',
    sellers: 'Sellers',
    management: 'Management',
    preferences: 'Preferences',
    darkMode: 'Dark mode',
    language: 'Language',
    privacySettings: 'Privacy settings',
    termsOfService: 'Terms of service',
    deleteAccount: 'Delete account',
    logout: 'Log out',
    adminProfile: 'Admin profile',
    editProfile: 'Edit profile',
    fullName: 'Full name',
    email: 'Email',
    changePhoto: 'Change photo',
    personalInfo: 'Personal info',
    security: 'Security',
    currentPassword: 'Current password',
    newPassword: 'New password',
    createPassword: 'Create password',
    confirmPassword: 'Confirm password',
    saving: 'Saving...',
    saveChanges: 'Save changes',
    profileUpdated: 'Profile updated successfully!',
    errorUpdatingProfile: 'Error updating profile.',
    passwordsDoNotMatch: 'Passwords do not match.',
    currentPasswordRequired: 'Current password is required.',
    reauthRequired: 'Reauthentication required. Please log out and log in again.',
    passwordRequiredForDeletion: 'Password required for deletion',
    privacyPolicy: 'Privacy Policy',
    dataProtection: 'Data Protection',
    privacyIntro: 'Your privacy is our priority. This policy explains how we collect, use, and protect your data.',
    dataCollection: 'Data Collection',
    dataCollectionText: 'We collect the following information to provide our services:',
    salesData: 'Sales Data',
    inventoryData: 'Inventory Data',
    dataSecurity: 'Data Security',
    dataSecurityText: 'We use end-to-end encryption and security best practices to protect your information.',
    lgpdCompliance: 'GDPR Compliance',
    lgpdText: 'We are in full compliance with data protection laws, ensuring your rights to access, rectification, and deletion.',
    lastUpdated: 'Last Updated',
    termsOfUse: 'Terms of Use',
    termsIntro: 'By using this application, you agree to the following terms and conditions.',
    acceptance: 'Acceptance of Terms',
    acceptanceText: 'Continued use of the service constitutes full acceptance of these terms.',
    userResponsibilities: 'User Responsibilities',
    userResponsibilitiesText: 'You are responsible for maintaining the confidentiality of your account and password.',
    limitationOfLiability: 'Limitation of Liability',
    limitationOfLiabilityText: 'We are not responsible for losses resulting from the improper use of the application.',
    warningTitle: 'Attention: Irreversible Action',
    deleteWarningText: 'By deleting your account, all your data (sales, history, profile) will be permanently removed from our servers. This action cannot be undone.',
    step1ExportData: 'Step 1: Export your Data',
    exportDataText: 'We recommend that you download a copy of all your records before proceeding.',
    downloadAllDataPDF: 'Download all data as PDF',
    step2ConfirmDeletion: 'Step 2: Confirm Deletion',
    enterPasswordToConfirm: 'Please enter your password to confirm it is you.',
    confirmPermanentDeletion: 'Confirm Permanent Deletion',
    deleting: 'Deleting...',
    errorDeletingAccount: 'Error deleting account.',
    passwordRequired: 'Password Required',
    mustCreatePasswordText: 'For your security, you must register a password in your profile before you can delete your account.',
    goToProfileToCreatePassword: 'Go to Profile to Create Password',
    dataExportTitle: 'Data Export Report',
    exportDate: 'Export Date',
    salesHistory: 'Sales History',
    cashMovements: 'Cash Movements',
    user: 'User',
    profileImage: 'Profile Image',
    passwordRequiredForDeletionError: 'You need to register a password in your profile before deleting the account.',
    stores: 'Stores',
    manageRetail: 'Manage retail locations',
    staffPermissions: 'Staff & team permissions',
    onTrack: 'On track',
    behind: 'Behind',
    completed: 'Completed',
    amount: 'Amount',
    paymentMethod: 'Payment method',
    seller: 'Seller',
    save: 'Save',
    delete: 'Delete',
    cancel: 'Cancel',
    removeSeller: 'Remove seller',
    editSeller: 'Edit seller',
    newSeller: 'New seller',
    sellerName: 'Seller name',
    contactPhone: 'Contact/phone',
    monthlySalesGoal: 'Monthly sales goal',
    observations: 'Observations',
    changePhoto: 'Change photo',
    allSellers: 'All sellers',
    activeSellers: 'Active sellers',
    searchSellers: 'Search sellers...',
    noSalesYet: 'No sales recorded yet.',
    viewAll: 'View all',
    today: 'Today',
    yesterday: 'Yesterday',
    thisMonth: 'This month',
    lastMonth: 'Last month',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    custom: 'Custom',
    selectDate: 'Select date',
    selectWeek: 'Select week',
    selectMonth: 'Select month',
    date: 'Date',
    time: 'Time',
    salesTrend: 'Sales trend',
    revenueByDay: 'Revenue by day',
    physicalStore: 'Physical store',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'Sales channels',
    performanceByPlatform: 'Performance by platform',
    total: 'Total',
    remaining: 'Remaining',
    currentSales: 'Current sales',
    recentGoalProgress: 'Recent goal progress',
    ofTargetReached: 'of target reached',
    monthlyProgress: 'Monthly progress',
    totalsByPaymentMethod: 'Totals by payment method',
    dailyView: 'Daily view',
    sellerPerformance: 'Seller performance',
    grandTotal: 'Grand total',
    salesToday: 'sales today',
    cash: 'Cash',
    credit: 'Credit',
    debit: 'Debit',
    pix: 'PIX',
    last7Days: 'Last 7 days',
    last30Days: 'Last 30 days',
    goalResult: 'Goal result',
    share: 'Share',
    teamMembers: 'Team members',
    addNew: 'Add new',
    noSellersYet: 'No sellers registered yet.',
    registerFirstSeller: 'Register first seller',
    goal: 'Goal',
    confirmRemoveSeller: 'Are you sure you want to remove this seller?',
    fullName: 'Full name',
    phonePlaceholder: '+1 (555) 000-0000',
    observationsPlaceholder: 'Add notes about performance, schedule, etc.',
    aiAssistant: 'AI assistant',
    scanReceipt: 'Scan a receipt to auto-fill the form',
    analyzing: 'Analyzing...',
    scan: 'Scan',
    saleDetails: 'Sale details',
    saving: 'Saving...',
    generating: 'Generating...',
    confirmSale: 'Confirm sale',
    achievementUnlocked: 'Achievement unlocked!',
    selectSeller: 'Select seller',
    saleSource: 'Sale source',
    cashBreakdown: 'Cash breakdown',
    totalCash: 'Total cash',
    confirmDeleteSale: 'Are you sure you want to delete this sale?',
    errorDeletingSale: 'Error deleting sale. Please try again.',
    noSalesFound: 'No sales found',
    bills: 'Bills',
    coins: 'Coins',
    performance: 'Performance',
    viewSale: 'View sale',
    print: 'Print',
    confirmDelete: 'Are you sure you want to delete this?',
    welcomeMessage: 'Professional sales performance dashboard',
    signInDescription: 'Sign in to access your dashboard and track your performance in real-time.',
    signInWithGoogle: 'Sign in with Google',
    authAgreement: 'By signing in, you agree to our Terms of Service and Privacy Policy.',
    applicationError: 'Application error',
    somethingWentWrong: 'Something went wrong.',
    permissionDenied: "You don't have permission to perform this action. Please ensure you are an administrator.",
    reloadApplication: 'Reload application',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    sun: 'Sun',
    w1: 'W1',
    w2: 'W2',
    w3: 'W3',
    w4: 'W4',
    bleed: 'Bleed',
    reinforcement: 'Reinforcement',
    releases: 'Releases',
    confirmMovement: 'Confirm movement',
    addNotes: 'Add notes/coins',
    observation: 'Observation',
    confirm: 'Confirm',
    paymentMethodDetail: 'Payment method detail',
    netCash: 'Net cash',
    totalSalesByMethod: 'Total sales',
    totalSangrias: 'Total sangrias',
    totalReforcos: 'Total reinforcements',
    calculatedCash: 'Calculated cash',
    summary: 'Summary',
    dailyReport: 'Daily report',
    downloadPDF: 'Download PDF',
    salesSummary: 'Sales summary',
    grossSales: 'Gross sales',
    discounts: 'Discounts',
    netTotal: 'Net total',
    transactions: 'Transactions',
    averageTicket: 'Average ticket',
    cashReconciliation: 'Cash reconciliation',
    cashReconciledSuccess: 'Cash reconciled successfully. No discrepancies found.',
    dailyGoal: 'Daily goal',
    achieved: 'Achieved',
    onlyMissing: 'Only missing',
    goalMet: 'Goal met!',
    exceededBy: 'Exceeded by',
    goalOfTheDay: 'Goal of the day',
    reportGeneratedAutomatically: 'Report generated automatically',
    ofReport: 'of report',
    of: 'of',
    card: 'Card',
    debitCredit: 'Debit/credit',
    pdf: 'PDF',
    unknown: 'Unknown',
    motivationalImage: 'Motivational image',
    profileImage: 'Profile image',
    user: 'User',
    email: 'Email',
    emailPlaceholder: 'seller@example.com',
    goalPlaceholder: '5000',
    preview: 'Preview',
    copiedToClipboard: 'Copied to clipboard!',
    detail: 'Detail',
    sale: 'Sale',
    cashSession: 'Cash session',
    opening: 'Opening',
    closing: 'Closing',
    openCash: 'Open cash',
    closeCash: 'Close cash',
    openingAmount: 'Opening amount',
    closingAmount: 'Closing amount',
    expected: 'Expected',
    difference: 'Difference',
    confirmOpening: 'Confirm opening',
    confirmClosing: 'Confirm closing',
    paymentLink: 'Payment link',
    exchangeVoucher: 'Exchange voucher',
    'payment-link': 'Payment link',
    'exchange-voucher': 'Exchange voucher',
    totalAmount: 'Total amount',
    noOpenSessionFound: 'No open session found to close',
    sessionAlreadyOpen: 'A session is already open',
    sessionDate: 'Session date',
    vs: 'vs',
    id: 'ID',
    loadingData: 'Loading persistent data...',
    amountPlaceholder: '0.00',
    salesHistory: 'Sales history',
    uploadSpreadsheet: 'Upload spreadsheet',
    extractingData: 'Extracting data...',
    extractedSales: 'Extracted sales',
    registerSales: 'Register sales',
    selectSalesToRegister: 'Select sales to register',
    value: 'Value',
    origin: 'Origin',
    selectAll: 'Select all',
    deselectAll: 'Deselect all',
    addPaymentMethod: 'Add payment method',
    remainingAmount: 'Remaining amount',
    totalPaid: 'Total paid',
    salesBySource: 'Sales by source',
    spreadsheet: 'Spreadsheet',
    upload: 'Upload',
    multiSelect: 'Multi-select',
    remove: 'Remove',
  },
  'pt-BR': {
    dashboard: 'Painel',
    entries: 'Lançamentos',
    history: 'Histórico',
    profile: 'Perfil',
    totalSales: 'Vendas totais',
    monthlyGoal: 'Meta mensal',
    recentSales: 'Vendas recentes',
    newSale: 'Nova venda',
    sellers: 'Vendedores',
    management: 'Gerenciamento',
    preferences: 'Preferências',
    darkMode: 'Modo escuro',
    language: 'Idioma',
    privacySettings: 'Configurações de privacidade',
    termsOfService: 'Termos de serviço',
    deleteAccount: 'Excluir conta',
    logout: 'Sair',
    adminProfile: 'Perfil do administrador',
    editProfile: 'Editar perfil',
    fullName: 'Nome completo',
    email: 'Email',
    changePhoto: 'Alterar foto',
    personalInfo: 'Informações pessoais',
    security: 'Segurança',
    currentPassword: 'Senha atual',
    newPassword: 'Nova senha',
    createPassword: 'Criar senha',
    confirmPassword: 'Confirmar senha',
    saving: 'Salvando...',
    saveChanges: 'Salvar alterações',
    profileUpdated: 'Perfil atualizado com sucesso!',
    errorUpdatingProfile: 'Erro ao atualizar perfil.',
    passwordsDoNotMatch: 'As senhas não coincidem.',
    currentPasswordRequired: 'Senha atual é obrigatória.',
    reauthRequired: 'Reautenticação necessária. Por favor, saia e entre novamente.',
    passwordRequiredForDeletion: 'Senha obrigatória para exclusão',
    privacyPolicy: 'Política de Privacidade',
    dataProtection: 'Proteção de Dados',
    privacyIntro: 'Sua privacidade é nossa prioridade. Esta política explica como coletamos, usamos e protegemos seus dados.',
    dataCollection: 'Coleta de Dados',
    dataCollectionText: 'Coletamos as seguintes informações para fornecer nossos serviços:',
    salesData: 'Dados de Vendas',
    inventoryData: 'Dados de Inventário',
    dataSecurity: 'Segurança dos Dados',
    dataSecurityText: 'Utilizamos criptografia de ponta a ponta e as melhores práticas de segurança para proteger suas informações.',
    lgpdCompliance: 'Conformidade com a LGPD',
    lgpdText: 'Estamos em total conformidade com a Lei Geral de Proteção de Dados (LGPD), garantindo seus direitos de acesso, retificação e exclusão.',
    lastUpdated: 'Última Atualização',
    termsOfUse: 'Termos de Uso',
    termsIntro: 'Ao utilizar este aplicativo, você concorda com os seguintes termos e condições.',
    acceptance: 'Aceitação dos Termos',
    acceptanceText: 'O uso continuado do serviço constitui aceitação total destes termos.',
    userResponsibilities: 'Responsabilidades do Usuário',
    userResponsibilitiesText: 'Você é responsável por manter a confidencialidade de sua conta e senha.',
    limitationOfLiability: 'Limitação de Responsabilidade',
    limitationOfLiabilityText: 'Não nos responsabilizamos por perdas decorrentes do uso indevido do aplicativo.',
    warningTitle: 'Atenção: Ação Irreversível',
    deleteWarningText: 'Ao excluir sua conta, todos os seus dados (vendas, histórico, perfil) serão removidos permanentemente de nossos servidores. Esta ação não pode ser desfeita.',
    step1ExportData: 'Passo 1: Exportar seus Dados',
    exportDataText: 'Recomendamos que você baixe uma cópia de todos os seus registros antes de prosseguir.',
    downloadAllDataPDF: 'Baixar todos os dados em PDF',
    step2ConfirmDeletion: 'Passo 2: Confirmar Exclusão',
    enterPasswordToConfirm: 'Por favor, digite sua senha para confirmar que é você.',
    confirmPermanentDeletion: 'Confirmar Exclusão Permanente',
    deleting: 'Excluindo...',
    errorDeletingAccount: 'Erro ao excluir conta.',
    passwordRequired: 'Senha Obrigatória',
    mustCreatePasswordText: 'Para sua segurança, você deve registrar uma senha em seu perfil antes de poder excluir sua conta.',
    goToProfileToCreatePassword: 'Ir para Perfil para Criar Senha',
    dataExportTitle: 'Relatório de Exportação de Dados',
    exportDate: 'Data de Exportação',
    salesHistory: 'Histórico de Vendas',
    cashMovements: 'Movimentações de Caixa',
    user: 'Usuário',
    profileImage: 'Imagem de perfil',
    passwordRequiredForDeletionError: 'Você precisa registrar uma senha no seu perfil antes de excluir a conta.',
    stores: 'Lojas',
    manageRetail: 'Gerenciar locais de varejo',
    staffPermissions: 'Equipe e permissões',
    onTrack: 'No prazo',
    behind: 'Atrasado',
    completed: 'Concluído',
    amount: 'Valor',
    paymentMethod: 'Método de pagamento',
    seller: 'Vendedor',
    save: 'Salvar',
    delete: 'Excluir',
    cancel: 'Cancelar',
    removeSeller: 'Remover vendedor',
    editSeller: 'Editar vendedor',
    newSeller: 'Novo vendedor',
    sellerName: 'Nome do vendedor',
    contactPhone: 'Contato/telefone',
    monthlySalesGoal: 'Meta de vendas mensal',
    observations: 'Observações',
    changePhoto: 'Alterar foto',
    allSellers: 'Todos os vendedores',
    activeSellers: 'Vendedores ativos',
    searchSellers: 'Buscar vendedores...',
    noSalesYet: 'Nenhuma venda registrada ainda.',
    viewAll: 'Ver tudo',
    today: 'Hoje',
    yesterday: 'Ontem',
    thisMonth: 'Este mês',
    lastMonth: 'Mês passado',
    day: 'Dia',
    week: 'Semana',
    month: 'Mês',
    custom: 'Personalizado',
    selectDate: 'Selecionar data',
    selectWeek: 'Selecionar semana',
    selectMonth: 'Selecionar mês',
    salesTrend: 'Tendência de vendas',
    revenueByDay: 'Receita por dia',
    physicalStore: 'Loja física',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'Canais de venda',
    performanceByPlatform: 'Desempenho por plataforma',
    total: 'Total',
    remaining: 'Restante',
    currentSales: 'Vendas atuais',
    recentGoalProgress: 'Progresso recente da meta',
    ofTargetReached: 'da meta alcançada',
    monthlyProgress: 'Progresso mensal',
    totalsByPaymentMethod: 'Totais por método de pagamento',
    dailyView: 'Visualização diária',
    sellerPerformance: 'Desempenho do vendedor',
    grandTotal: 'Total geral',
    salesToday: 'vendas hoje',
    cash: 'Dinheiro',
    credit: 'Crédito',
    debit: 'Débito',
    pix: 'PIX',
    last7Days: 'Últimos 7 dias',
    last30Days: 'Últimos 30 dias',
    goalResult: 'Resultado da meta',
    share: 'Compartilhar',
    teamMembers: 'Membros da equipe',
    addNew: 'Adicionar novo',
    noSellersYet: 'Nenhum vendedor registrado ainda.',
    registerFirstSeller: 'Registrar primeiro vendedor',
    goal: 'Meta',
    confirmRemoveSeller: 'Tem certeza que deseja remover este vendedor?',
    fullName: 'Nome completo',
    phonePlaceholder: '(00) 00000-0000',
    observationsPlaceholder: 'Adicione notas sobre desempenho, horário, etc.',
    aiAssistant: 'Assistente de IA',
    scanReceipt: 'Escaneie um recibo para preencher o formulário',
    analyzing: 'Analisando...',
    scan: 'Escanear',
    saleDetails: 'Detalhes da venda',
    saving: 'Salvando...',
    generating: 'Gerando...',
    confirmSale: 'Confirmar venda',
    achievementUnlocked: 'Conquista desbloqueada!',
    selectSeller: 'Selecionar vendedor',
    saleSource: 'Fonte da venda',
    cashBreakdown: 'Detalhamento de dinheiro',
    totalCash: 'Total em dinheiro',
    confirmDeleteSale: 'Tem certeza que deseja excluir esta venda?',
    errorDeletingSale: 'Erro ao excluir venda. Tente novamente.',
    noSalesFound: 'Nenhuma venda encontrada',
    bills: 'Notas',
    coins: 'Moedas',
    performance: 'Desempenho',
    viewSale: 'Ver venda',
    print: 'Imprimir',
    confirmDelete: 'Tem certeza que deseja excluir?',
    welcomeMessage: 'Painel profissional de desempenho de vendas',
    signInDescription: 'Faça login para acessar seu painel e acompanhar seu desempenho em tempo real.',
    signInWithGoogle: 'Entrar com Google',
    authAgreement: 'Ao entrar, você concorda com nossos Termos de Serviço e Política de Privacidade.',
    applicationError: 'Erro na aplicação',
    somethingWentWrong: 'Algo deu errado.',
    permissionDenied: 'Você não tem permissão para realizar esta ação. Certifique-se de que você é um administrador.',
    reloadApplication: 'Recarregar aplicação',
    mon: 'Seg',
    tue: 'Ter',
    wed: 'Qua',
    thu: 'Qui',
    fri: 'Sex',
    sat: 'Sáb',
    sun: 'Dom',
    w1: 'S1',
    w2: 'S2',
    w3: 'S3',
    w4: 'S4',
    releases: 'Lançamentos',
    bleed: 'Sangria',
    reinforcement: 'Reforço',
    confirmMovement: 'Confirmar movimentação',
    addNotes: 'Adicionar notas/moedas',
    observation: 'Observação',
    confirm: 'Confirmar',
    paymentMethodDetail: 'Detalhes do método de pagamento',
    netCash: 'Dinheiro líquido',
    totalSalesByMethod: 'Vendas totais',
    totalSangrias: 'Total de sangrias',
    totalReforcos: 'Total de reforços',
    calculatedCash: 'Dinheiro calculado',
    summary: 'Resumo',
    dailyReport: 'Relatório diário',
    downloadPDF: 'Baixar PDF',
    salesSummary: 'Resumo de vendas',
    grossSales: 'Vendas brutas',
    discounts: 'Descontos',
    netTotal: 'Total líquido',
    transactions: 'Transações',
    averageTicket: 'Ticket médio',
    cashReconciliation: 'Reconciliação de caixa',
    cashReconciledSuccess: 'Caixa reconciliado com sucesso. Nenhuma divergência encontrada.',
    dailyGoal: 'Meta diária',
    achieved: 'Atingido',
    onlyMissing: 'Faltam apenas',
    goalMet: 'Meta batida!',
    exceededBy: 'Passou em',
    goalOfTheDay: 'Meta do dia',
    reportGeneratedAutomatically: 'Relatório gerado automaticamente',
    ofReport: 'do relatório',
    of: 'de',
    card: 'Cartão',
    debitCredit: 'Débito/crédito',
    pdf: 'PDF',
    unknown: 'Desconhecido',
    motivationalImage: 'Imagem motivacional',
    profileImage: 'Imagem de perfil',
    user: 'Usuário',
    email: 'Email',
    emailPlaceholder: 'vendedor@exemplo.com',
    goalPlaceholder: '5000',
    preview: 'Prévia',
    copiedToClipboard: 'Copiado para a área de transferência!',
    detail: 'Detalhe',
    sale: 'Venda',
    cashSession: 'Sessão de caixa',
    opening: 'Abertura',
    closing: 'Fechamento',
    openCash: 'Abrir caixa',
    closeCash: 'Fechar caixa',
    openingAmount: 'Valor de abertura',
    closingAmount: 'Valor de fechamento',
    expected: 'Esperado',
    difference: 'Diferença',
    confirmOpening: 'Confirmar abertura',
    confirmClosing: 'Confirmar fechamento',
    paymentLink: 'Link de pagamento',
    exchangeVoucher: 'Vale troca',
    'payment-link': 'Link de pagamento',
    'exchange-voucher': 'Vale troca',
    totalAmount: 'Valor total',
    noOpenSessionFound: 'Nenhuma sessão aberta encontrada para fechar',
    sessionAlreadyOpen: 'Já existe uma sessão aberta',
    sessionDate: 'Data da sessão',
    vs: 'vs',
    id: 'ID',
    loadingData: 'Carregando dados persistentes...',
    amountPlaceholder: '0,00',
    salesHistory: 'Histórico de vendas',
    uploadSpreadsheet: 'Carregar planilha',
    extractingData: 'Extraindo dados...',
    extractedSales: 'Vendas extraídas',
    registerSales: 'Registrar vendas',
    selectSalesToRegister: 'Selecione as vendas para registrar',
    date: 'Data',
    time: 'Hora',
    value: 'Valor',
    origin: 'Origem',
    selectAll: 'Selecionar tudo',
    deselectAll: 'Desmarcar tudo',
    addPaymentMethod: 'Adicionar método de pagamento',
    remainingAmount: 'Valor restante',
    totalPaid: 'Total pago',
    salesBySource: 'Vendas por origem',
    spreadsheet: 'Planilha',
    upload: 'Carregar',
    multiSelect: 'Seleção múltipla',
    remove: 'Remover',
  },
  fr: {
    dashboard: 'Tableau de bord',
    entries: 'Entrées',
    history: 'Historique',
    profile: 'Profil',
    totalSales: 'Ventes totales',
    monthlyGoal: 'Objectif mensuel',
    recentSales: 'Ventes récentes',
    newSale: 'Nouvelle vente',
    sellers: 'Vendeurs',
    management: 'Gestion',
    preferences: 'Préférences',
    darkMode: 'Mode sombre',
    language: 'Langue',
    privacySettings: 'Paramètres de confidentialité',
    termsOfService: 'Conditions d\'utilisation',
    deleteAccount: 'Supprimer le compte',
    logout: 'Se déconnecter',
    adminProfile: 'Profil administrateur',
    editProfile: 'Modifier le profil',
    stores: 'Magasins',
    manageRetail: 'Gérer les points de vente',
    staffPermissions: 'Personnel et autorisations',
    onTrack: 'Sur la bonne voie',
    behind: 'En retard',
    completed: 'Terminé',
    amount: 'Montant',
    paymentMethod: 'Mode de paiement',
    seller: 'Vendeur',
    save: 'Enregistrer',
    cancel: 'Annuler',
    removeSeller: 'Supprimer le vendeur',
    editSeller: 'Modifier le vendeur',
    newSeller: 'Nouveau vendeur',
    sellerName: 'Nom du vendeur',
    contactPhone: 'Contact/Téléphone',
    monthlySalesGoal: 'Objectif de vente mensuel',
    observations: 'Observations',
    changePhoto: 'Changer la photo',
    allSellers: 'Tous les vendeurs',
    activeSellers: 'Vendeurs actifs',
    searchSellers: 'Rechercher des vendeurs...',
    noSalesYet: 'Aucune vente enregistrée.',
    viewAll: 'Voir tout',
    today: 'Aujourd\'hui',
    yesterday: 'Hier',
    thisMonth: 'Ce mois-ci',
    lastMonth: 'Le mois dernier',
    day: 'Jour',
    week: 'Semaine',
    month: 'Mois',
    custom: 'Personnalisé',
    selectDate: 'Choisir une date',
    selectWeek: 'Choisir une semaine',
    selectMonth: 'Choisir un mois',
    date: 'Date',
    time: 'Heure',
    salesTrend: 'Tendance des ventes',
    revenueByDay: 'Revenu par jour',
    physicalStore: 'Magasin physique',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'Canaux de vente',
    performanceByPlatform: 'Performance par plateforme',
    total: 'Total',
    remaining: 'Restant',
    currentSales: 'Vendas atuais',
    recentGoalProgress: 'Progrès récent des objectifs',
    ofTargetReached: 'de l\'objectif atteint',
    monthlyProgress: 'Progrès mensuel',
    totalsByPaymentMethod: 'Totaux par mode de paiement',
    dailyView: 'Vue quotidienne',
    sellerPerformance: 'Performance du vendeur',
    grandTotal: 'Total général',
    salesToday: 'ventes aujourd\'hui',
    cash: 'Espèces',
    credit: 'Crédit',
    debit: 'Débit',
    pix: 'PIX',
    last7Days: '7 derniers jours',
    last30Days: '30 derniers jours',
    goalResult: 'Résultat de l\'objectif',
    share: 'Partager',
    teamMembers: 'Membres de l\'équipe',
    addNew: 'Ajouter nouveau',
    noSellersYet: 'Aucun vendeur enregistré.',
    registerFirstSeller: 'Enregistrer le premier vendeur',
    goal: 'Objectif',
    confirmRemoveSeller: 'Voulez-vous vraiment supprimer ce vendeur ?',
    fullName: 'Nom complet',
    phonePlaceholder: '+33 0 00 00 00 00',
    observationsPlaceholder: 'Ajouter des notes sur la performance, etc.',
    aiAssistant: 'Assistant IA',
    scanReceipt: 'Scanner un reçu pour remplir le formulaire',
    uploadSpreadsheet: 'Télécharger une feuille de calcul',
    extractingData: 'Extraction des données...',
    extractedSales: 'Ventes extraites',
    registerSales: 'Enregistrer les ventes',
    selectSalesToRegister: 'Sélectionnez les ventes à enregistrer',
    value: 'Valeur',
    origin: 'Origine',
    noSalesFound: 'Aucune vente trouvée',
    selectAll: 'Tout sélectionner',
    deselectAll: 'Tout déselectionner',
    analyzing: 'Analyse...',
    scan: 'Scanner',
    saleDetails: 'Détails de la vente',
    saving: 'Enregistrement...',
    confirmSale: 'Confirmer la vente',
    achievementUnlocked: 'Succès déverrouillé !',
    welcomeMessage: 'Tableau de bord professionnel des ventes',
    signInDescription: 'Connectez-vous pour accéder à votre tableau de bord.',
    signInWithGoogle: 'Se connecter avec Google',
    authAgreement: 'En vous connectant, vous acceptez nos conditions.',
    applicationError: 'Erreur d\'application',
    somethingWentWrong: 'Quelque chose s\'est mal passé.',
    permissionDenied: 'Vous n\'avez pas la permission.',
    reloadApplication: 'Recharger l\'application',
    releases: 'Lancements',
    bleed: 'Prélèvement',
    reinforcement: 'Renforcement',
    confirmMovement: 'Confirmer le mouvement',
    addNotes: 'Ajouter des billets/pièces',
    observation: 'Observation',
    confirm: 'Confirmer',
    paymentMethodDetail: 'Détail du mode de paiement',
    netCash: 'Espèces nettes',
    totalSalesByMethod: 'Ventes totales',
    totalSangrias: 'Total des prélèvements',
    totalReforcos: 'Total des renforcements',
    calculatedCash: 'Espèces calculées',
    summary: 'Résumé',
    dailyReport: 'Rapport journalier',
    downloadPDF: 'Télécharger le PDF',
    salesSummary: 'Résumé des ventes',
    grossSales: 'Ventes brutes',
    discounts: 'Remises',
    netTotal: 'Total net',
    transactions: 'Transactions',
    averageTicket: 'Panier moyen',
    cashReconciliation: 'Réconciliation de caisse',
    cashReconciledSuccess: 'Caisse réconciliée avec succès. Aucune divergence trouvée.',
    dailyGoal: 'Objectif journalier',
    achieved: 'Atteint',
    onlyMissing: 'Il ne manque que',
    goalMet: 'Objectif atteint !',
    exceededBy: 'Dépassé de',
    goalOfTheDay: 'Objectif du jour',
    reportGeneratedAutomatically: 'Rapport généré automatiquement',
    ofReport: 'du rapport',
    of: 'de',
    card: 'Carte',
    debitCredit: 'Débit/crédit',
    pdf: 'PDF',
    unknown: 'Inconnu',
    motivationalImage: 'Image de motivation',
    profileImage: 'Image de profil',
    user: 'Utilisateur',
    email: 'Email',
    emailPlaceholder: 'vendeur@exemple.com',
    goalPlaceholder: '5000',
    preview: 'Aperçu',
    copiedToClipboard: 'Copié dans le presse-papier !',
    detail: 'Détail',
    sale: 'Vente',
    cashSession: 'Session de caisse',
    opening: 'Ouverture',
    closing: 'Clôture',
    openCash: 'Ouvrir la Caisse',
    closeCash: 'Fermer la Caisse',
    openingAmount: 'Montant d\'ouverture',
    closingAmount: 'Montant de fermeture',
    expected: 'Attendu',
    difference: 'Différence',
    confirmOpening: 'Confirmer l\'ouverture',
    confirmClosing: 'Confirmer la fermeture',
    paymentLink: 'Lien de paiement',
    exchangeVoucher: 'Bon d\'échange',
    'payment-link': 'Lien de paiement',
    'exchange-voucher': 'Bon d\'échange',
    totalAmount: 'Montant total',
    addPaymentMethod: 'Ajouter un mode de paiement',
    remainingAmount: 'Montant restant',
    totalPaid: 'Total payé',
    salesBySource: 'Ventes par source',
    spreadsheet: 'Feuille de calcul',
    upload: 'Télécharger',
    noOpenSessionFound: 'Aucune session ouverte trouvée pour fermer',
    sessionAlreadyOpen: 'Une session est déjà ouverte',
    sessionDate: 'Date de la Session',
    vs: 'vs',
    id: 'ID',
    loadingData: 'Chargement des données persistantes...',
    salesHistory: 'Historique des ventes',
  },
  es: {
    dashboard: 'Tablero',
    entries: 'Entradas',
    history: 'Historial',
    profile: 'Perfil',
    totalSales: 'Ventas totales',
    monthlyGoal: 'Meta mensual',
    recentSales: 'Ventas recientes',
    newSale: 'Nueva venta',
    sellers: 'Vendedores',
    management: 'Gestión',
    preferences: 'Preferencias',
    darkMode: 'Modo oscuro',
    language: 'Idioma',
    privacySettings: 'Ajustes de privacidad',
    termsOfService: 'Términos de servicio',
    deleteAccount: 'Eliminar cuenta',
    logout: 'Cerrar sesión',
    adminProfile: 'Perfil de administrador',
    editProfile: 'Editar perfil',
    fullName: 'Nombre completo',
    email: 'Correo electrónico',
    changePhoto: 'Cambiar foto',
    personalInfo: 'Información personal',
    security: 'Seguridad',
    currentPassword: 'Contraseña actual',
    newPassword: 'Nueva contraseña',
    createPassword: 'Crear contraseña',
    confirmPassword: 'Confirmar contraseña',
    saving: 'Guardando...',
    saveChanges: 'Guardar cambios',
    profileUpdated: '¡Perfil actualizado con éxito!',
    errorUpdatingProfile: 'Error al actualizar el perfil.',
    passwordsDoNotMatch: 'Las contraseñas no coinciden.',
    currentPasswordRequired: 'La contraseña actual es obligatoria.',
    reauthRequired: 'Reautenticación necesaria. Por favor, cierre la sesión y vuelva a entrar.',
    passwordRequiredForDeletion: 'Contraseña obligatoria para eliminación',
    privacyPolicy: 'Política de Privacidad',
    dataProtection: 'Protección de Datos',
    privacyIntro: 'Su privacidad es nuestra prioridad. Esta política explica cómo recopilamos, usamos y protegemos sus datos.',
    dataCollection: 'Recopilación de Datos',
    dataCollectionText: 'Recopilamos la siguiente información para proporcionar nuestros servicios:',
    salesData: 'Datos de Ventas',
    inventoryData: 'Datos de Inventario',
    dataSecurity: 'Seguridad de Datos',
    dataSecurityText: 'Utilizamos cifrado de extremo a extremo y las mejores prácticas de seguridad para proteger su información.',
    lgpdCompliance: 'Cumplimiento de la LGPD',
    lgpdText: 'Cumplimos plenamente con la Ley General de Protección de Datos (LGPD), garantizando sus derechos de acceso, rectificación y eliminación.',
    lastUpdated: 'Última Actualización',
    termsOfUse: 'Términos de Uso',
    termsIntro: 'Al utilizar esta aplicación, usted acepta los siguientes términos y condiciones.',
    acceptance: 'Aceptación de los Términos',
    acceptanceText: 'El uso continuado del servicio constituye la aceptación total de estos términos.',
    userResponsibilities: 'Responsabilidades del Usuario',
    userResponsibilitiesText: 'Usted es responsable de mantener la confidencialidad de su cuenta y contraseña.',
    limitationOfLiability: 'Limitación de Responsabilidad',
    limitationOfLiabilityText: 'No nos responsabilizamos por pérdidas derivadas del uso indebido de la aplicación.',
    warningTitle: 'Atención: Acción Irreversible',
    deleteWarningText: 'Al eliminar su cuenta, todos sus datos (ventas, historial, perfil) se eliminarán permanentemente de nuestros servidores. Esta acción no se puede deshacer.',
    step1ExportData: 'Paso 1: Exportar sus Datos',
    exportDataText: 'Le recomendamos que descargue una copia de todos sus registros antes de continuar.',
    downloadAllDataPDF: 'Descargar todos los datos en PDF',
    step2ConfirmDeletion: 'Paso 2: Confirmar Eliminación',
    enterPasswordToConfirm: 'Por favor, ingrese su contraseña para confirmar que es usted.',
    confirmPermanentDeletion: 'Confirmar Eliminación Permanente',
    deleting: 'Eliminando...',
    errorDeletingAccount: 'Error al eliminar la cuenta.',
    passwordRequired: 'Contraseña Obligatoria',
    mustCreatePasswordText: 'Para su seguridad, debe registrar una contraseña en su perfil antes de poder eliminar su cuenta.',
    goToProfileToCreatePassword: 'Ir al Perfil para Crear Contraseña',
    dataExportTitle: 'Informe de Exportación de Datos',
    exportDate: 'Fecha de Exportación',
    salesHistory: 'Historial de Ventas',
    cashMovements: 'Movimientos de Caja',
    user: 'Usuario',
    profileImage: 'Imagen de perfil',
    passwordRequiredForDeletionError: 'Debe registrar una contraseña en su perfil antes de eliminar la cuenta.',
    stores: 'Tiendas',
    manageRetail: 'Gestionar ubicaciones minoristas',
    staffPermissions: 'Personal y permisos',
    onTrack: 'En marcha',
    behind: 'Atrasado',
    completed: 'Completado',
    amount: 'Monto',
    paymentMethod: 'Método de pago',
    seller: 'Vendedor',
    save: 'Guardar',
    cancel: 'Cancelar',
    removeSeller: 'Eliminar vendedor',
    editSeller: 'Editar vendedor',
    newSeller: 'Nuevo vendedor',
    sellerName: 'Nombre del vendedor',
    contactPhone: 'Contacto/Teléfono',
    monthlySalesGoal: 'Meta de ventas mensual',
    observations: 'Observaciones',
    allSellers: 'Todos los vendedores',
    activeSellers: 'Vendedores activos',
    searchSellers: 'Buscar vendedores...',
    noSalesYet: 'No hay ventas registradas.',
    viewAll: 'Ver todo',
    today: 'Hoy',
    yesterday: 'Ayer',
    thisMonth: 'Este mes',
    lastMonth: 'Mes pasado',
    day: 'Día',
    week: 'Semana',
    month: 'Mes',
    custom: 'Personalizado',
    selectDate: 'Seleccionar fecha',
    selectWeek: 'Seleccionar semana',
    selectMonth: 'Seleccionar mes',
    date: 'Fecha',
    time: 'Hora',
    salesTrend: 'Tendencia de ventas',
    revenueByDay: 'Ingresos por día',
    physicalStore: 'Tienda física',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'Canales de venta',
    performanceByPlatform: 'Rendimiento por plataforma',
    total: 'Total',
    remaining: 'Restante',
    currentSales: 'Ventas actuales',
    recentGoalProgress: 'Progreso reciente de metas',
    ofTargetReached: 'del objetivo alcanzado',
    monthlyProgress: 'Progreso mensual',
    totalsByPaymentMethod: 'Totales por método de pago',
    dailyView: 'Vista diaria',
    sellerPerformance: 'Rendimiento del vendedor',
    grandTotal: 'Gran total',
    salesToday: 'ventas hoy',
    cash: 'Efectivo',
    credit: 'Crédito',
    debit: 'Débito',
    pix: 'PIX',
    last7Days: 'Últimos 7 días',
    last30Days: 'Últimos 30 días',
    goalResult: 'Resultado de meta',
    share: 'Compartir',
    teamMembers: 'Miembros del equipo',
    addNew: 'Agregar nuevo',
    noSellersYet: 'No hay vendedores registrados.',
    registerFirstSeller: 'Registrar primer vendedor',
    goal: 'Meta',
    confirmRemoveSeller: '¿Estás seguro de eliminar este vendedor?',
    phonePlaceholder: '+34 000 000 000',
    observationsPlaceholder: 'Agregar notas sobre el rendimiento, etc.',
    aiAssistant: 'Asistente de IA',
    scanReceipt: 'Escanear un recibo para completar el formulario',
    uploadSpreadsheet: 'Cargar hoja de cálculo',
    noSalesFound: 'No se encontraron ventas',
    analyzing: 'Analizando...',
    scan: 'Escanear',
    saleDetails: 'Detalles de la venta',
    confirmSale: 'Confirmar venta',
    achievementUnlocked: '¡Logro desbloqueado!',
    welcomeMessage: 'Tablero profesional de ventas',
    signInDescription: 'Inicia sesión para acceder a tu tablero.',
    signInWithGoogle: 'Iniciar sesión con Google',
    authAgreement: 'Al iniciar sesión, aceptas nuestros términos.',
    applicationError: 'Error de aplicación',
    somethingWentWrong: 'Algo salió mal.',
    permissionDenied: 'No tienes permiso.',
    reloadApplication: 'Recargar aplicación',
    releases: 'Lanzamientos',
    bleed: 'Sangría',
    reinforcement: 'Refuerzo',
    confirmMovement: 'Confirmar movimiento',
    addNotes: 'Agregar billetes/monedas',
    observation: 'Observación',
    confirm: 'Confirmar',
    paymentMethodDetail: 'Detalles del método de pago',
    netCash: 'Efectivo neto',
    totalSalesByMethod: 'Ventas totales',
    totalSangrias: 'Total de sangrías',
    totalReforcos: 'Total de refuerzos',
    calculatedCash: 'Efectivo calculado',
    summary: 'Resumen',
    dailyReport: 'Informe diario',
    downloadPDF: 'Descargar PDF',
    salesSummary: 'Resumen de ventas',
    grossSales: 'Ventas brutas',
    discounts: 'Descuentos',
    netTotal: 'Total neto',
    transactions: 'Transacciones',
    averageTicket: 'Ticket promedio',
    cashReconciliation: 'Reconciliación de caja',
    cashReconciledSuccess: 'Caja reconciliada con éxito. No se encontraron discrepancias.',
    dailyGoal: 'Meta diaria',
    achieved: 'Alcanzado',
    onlyMissing: 'Solo faltan',
    goalMet: '¡Meta alcanzada!',
    exceededBy: 'Superado por',
    goalOfTheDay: 'Meta del día',
    reportGeneratedAutomatically: 'Informe generado automáticamente',
    ofReport: 'del informe',
    of: 'de',
    card: 'Tarjeta',
    debitCredit: 'Débito/crédito',
    pdf: 'PDF',
    unknown: 'Desconocido',
    motivationalImage: 'Imagen motivacional',
    emailPlaceholder: 'vendedor@ejemplo.com',
    goalPlaceholder: '5000',
    preview: 'Vista previa',
    copiedToClipboard: '¡Copiado al portapapeles!',
    detail: 'Detalle',
    sale: 'Venta',
    cashSession: 'Sesión de caja',
    opening: 'Apertura',
    closing: 'Cierre',
    openCash: 'Abrir Caja',
    closeCash: 'Cerrar Caja',
    openingAmount: 'Monto de apertura',
    closingAmount: 'Monto de cierre',
    expected: 'Esperado',
    difference: 'Diferencia',
    confirmOpening: 'Confirmar apertura',
    confirmClosing: 'Confirmar cierre',
    paymentLink: 'Enlace de pago',
    exchangeVoucher: 'Vale de canje',
    'payment-link': 'Enlace de pago',
    'exchange-voucher': 'Vale de canje',
    totalAmount: 'Monto total',
    addPaymentMethod: 'Agregar método de pago',
    remainingAmount: 'Monto restante',
    totalPaid: 'Total pagado',
    salesBySource: 'Ventas por origen',
    spreadsheet: 'Hoja de cálculo',
    upload: 'Cargar',
    noOpenSessionFound: 'No se encontró ninguna sesión abierta para cerrar',
    sessionAlreadyOpen: 'Ya hay una sesión abierta',
    sessionDate: 'Fecha de la sesión',
    vs: 'vs',
    id: 'ID',
    loadingData: 'Cargando datos persistentes...',
    amountPlaceholder: '0,00',
    salesHistory: 'Historial de ventas',
  },
  de: {
    dashboard: 'Dashboard',
    entries: 'Einträge',
    history: 'Verlauf',
    profile: 'Profil',
    totalSales: 'Gesamtumsatz',
    monthlyGoal: 'Monatsziel',
    recentSales: 'Aktuelle Verkäufe',
    newSale: 'Neuer Verkauf',
    sellers: 'Verkäufer',
    management: 'Verwaltung',
    preferences: 'Einstellungen',
    darkMode: 'Dunkelmodus',
    language: 'Sprache',
    privacySettings: 'Datenschutz',
    termsOfService: 'Nutzungsbedingungen',
    deleteAccount: 'Konto löschen',
    logout: 'Abmelden',
    adminProfile: 'Admin-Profil',
    editProfile: 'Profil bearbeiten',
    stores: 'Filialen',
    manageRetail: 'Einzelhandelsstandorte verwalten',
    staffPermissions: 'Personal & Berechtigungen',
    onTrack: 'Im Plan',
    behind: 'Im Verzug',
    completed: 'Abgeschlossen',
    amount: 'Betrag',
    paymentMethod: 'Zahlungsart',
    seller: 'Verkäufer',
    save: 'Speichern',
    cancel: 'Abbrechen',
    removeSeller: 'Verkäufer entfernen',
    editSeller: 'Verkäufer bearbeiten',
    newSeller: 'Neuer Verkäufer',
    sellerName: 'Name des Verkäufers',
    contactPhone: 'Kontakt/Telefon',
    monthlySalesGoal: 'Monatliches Verkaufsziel',
    observations: 'Beobachtungen',
    changePhoto: 'Foto ändern',
    allSellers: 'Alle Verkäufer',
    activeSellers: 'Aktive Verkäufer',
    searchSellers: 'Verkäufer suchen...',
    noSalesYet: 'Noch keine Verkäufe.',
    viewAll: 'Alle anzeigen',
    today: 'Heute',
    yesterday: 'Gestern',
    thisMonth: 'Diesen Monat',
    lastMonth: 'Letzten Monat',
    day: 'Tag',
    week: 'Woche',
    month: 'Monat',
    custom: 'Benutzerdefiniert',
    selectDate: 'Datum auswählen',
    selectWeek: 'Woche auswählen',
    selectMonth: 'Monat auswählen',
    date: 'Datum',
    time: 'Uhrzeit',
    salesTrend: 'Verkaufstrend',
    revenueByDay: 'Umsatz nach Tag',
    physicalStore: 'Ladengeschäft',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'Verkaufskanäle',
    performanceByPlatform: 'Leistung nach Plattform',
    total: 'Gesamt',
    remaining: 'Verbleibend',
    currentSales: 'Aktuelle Verkäufe',
    recentGoalProgress: 'Aktueller Zielfortschritt',
    ofTargetReached: 'des Ziels erreicht',
    monthlyProgress: 'Monatlicher Fortschritt',
    totalsByPaymentMethod: 'Gesamtbeträge nach Zahlungsart',
    dailyView: 'Tagesansicht',
    sellerPerformance: 'Verkäuferleistung',
    grandTotal: 'Gesamtsumme',
    salesToday: 'Verkäufe heute',
    cash: 'Bar',
    credit: 'Kredit',
    debit: 'Lastschrift',
    pix: 'PIX',
    last7Days: 'Letzte 7 Tage',
    last30Days: 'Letzte 30 Tage',
    goalResult: 'Zielergebnis',
    share: 'Teilen',
    teamMembers: 'Teammitglieder',
    addNew: 'Neu hinzufügen',
    noSellersYet: 'Noch keine Verkäufer registriert.',
    registerFirstSeller: 'Ersten Verkäufer registrieren',
    goal: 'Ziel',
    confirmRemoveSeller: 'Sind Sie sicher, dass Sie diesen Verkäufer entfernen möchten?',
    fullName: 'Vollständiger Name',
    phonePlaceholder: '+49 000 00000000',
    observationsPlaceholder: 'Notizen zur Leistung, Zeitplan usw. hinzufügen',
    aiAssistant: 'KI-Assistent',
    scanReceipt: 'Beleg scannen, um das Formular automatisch auszufüllen',
    uploadSpreadsheet: 'Tabelle hochladen',
    extractingData: 'Daten werden extrahiert...',
    extractedSales: 'Extrahierte Verkäufe',
    registerSales: 'Verkäufe registrieren',
    selectSalesToRegister: 'Wählen Sie die zu registrierenden Verkäufe aus',
    value: 'Wert',
    origin: 'Herkunft',
    noSalesFound: 'Keine Verkäufe gefunden',
    selectAll: 'Alles auswählen',
    deselectAll: 'Alles abwählen',
    analyzing: 'Analysiere...',
    scan: 'Scannen',
    saleDetails: 'Verkaufsdetails',
    saving: 'Speichere...',
    confirmSale: 'Verkauf bestätigen',
    achievementUnlocked: 'Erfolg freigeschaltet!',
    welcomeMessage: 'Professionelles Verkaufs-Dashboard',
    signInDescription: 'Melden Sie sich an, um auf Ihr Dashboard zuzugreifen.',
    signInWithGoogle: 'Mit Google anmelden',
    authAgreement: 'Mit der Anmeldung stimmen Sie unseren Bedingungen zu.',
    applicationError: 'Anwendungsfehler',
    somethingWentWrong: 'Etwas ist schief gelaufen.',
    permissionDenied: 'Keine Berechtigung.',
    reloadApplication: 'Anwendung neu laden',
    mon: 'Mo',
    tue: 'Di',
    wed: 'Mi',
    thu: 'Do',
    fri: 'Fr',
    sat: 'Sa',
    sun: 'So',
    w1: 'W1',
    w2: 'W2',
    w3: 'W3',
    w4: 'W4',
    releases: 'Releases',
    bleed: 'Entnahme',
    reinforcement: 'Einlage',
    confirmMovement: 'Bewegung bestätigen',
    addNotes: 'Scheine/Münzen hinzufügen',
    observation: 'Beobachtung',
    confirm: 'Bestätigen',
    paymentMethodDetail: 'Details zur Zahlungsart',
    netCash: 'Netto-Bargeld',
    totalSalesByMethod: 'Gesamtumsatz',
    totalSangrias: 'Gesamtentnahmen',
    totalReforcos: 'Gesamteinlagen',
    calculatedCash: 'Berechnetes Bargeld',
    summary: 'Zusammenfassung',
    dailyReport: 'Tagesbericht',
    closing: 'Abschluss',
    downloadPDF: 'PDF herunterladen',
    salesSummary: 'Verkaufszusammenfassung',
    grossSales: 'Bruttoumsatz',
    discounts: 'Rabatte',
    netTotal: 'Nettogesamtsumme',
    transactions: 'Transaktionen',
    averageTicket: 'Durchschnittlicher Bon',
    cashReconciliation: 'Kassenabgleich',
    cashReconciledSuccess: 'Kasse erfolgreich abgeglichen. Keine Unstimmigkeiten gefunden.',
    dailyGoal: 'Tagesziel',
    achieved: 'Erreicht',
    onlyMissing: 'Es fehlen nur noch',
    goalMet: 'Ziel erreicht!',
    exceededBy: 'Überschritten um',
    goalOfTheDay: 'Tagesziel',
    reportGeneratedAutomatically: 'Bericht automatisch generiert',
    ofReport: 'des Berichts',
    of: 'von',
    card: 'Karte',
    debitCredit: 'Lastschrift/Kredit',
    pdf: 'PDF',
    unknown: 'Unbekannt',
    motivationalImage: 'Motivationsbild',
    profileImage: 'Profilbild',
    user: 'Benutzer',
    email: 'E-Mail',
    emailPlaceholder: 'verkaeufer@beispiel.de',
    goalPlaceholder: '5000',
    preview: 'Vorschau',
    copiedToClipboard: 'In die Zwischenablage kopiert!',
    detail: 'Detail',
    sale: 'Verkauf',
    cashSession: 'Kassensitzung',
    opening: 'Eröffnung',
    openCash: 'Kasse öffnen',
    closeCash: 'Kasse schließen',
    openingAmount: 'Eröffnungsbetrag',
    closingAmount: 'Abschlussbetrag',
    expected: 'Erwartet',
    difference: 'Differenz',
    confirmOpening: 'Eröffnung bestätigen',
    confirmClosing: 'Abschluss bestätigen',
    paymentLink: 'Zahlungslink',
    exchangeVoucher: 'Umtauschbeleg',
    'payment-link': 'Zahlungslink',
    'exchange-voucher': 'Umtauschbeleg',
    totalAmount: 'Gesamtbetrag',
    addPaymentMethod: 'Zahlungsart hinzufügen',
    remainingAmount: 'Verbleibender Betrag',
    totalPaid: 'Gesamt bezahlt',
    salesBySource: 'Verkäufe nach Herkunft',
    spreadsheet: 'Tabelle',
    upload: 'Hochladen',
    noOpenSessionFound: 'Keine offene Sitzung zum Schließen gefunden',
    sessionAlreadyOpen: 'Eine Sitzung ist bereits offen',
    sessionDate: 'Sitzungsdatum',
    vs: 'vs',
    id: 'ID',
    loadingData: 'Lade persistente Daten...',
    amountPlaceholder: '0,00',
    salesHistory: 'Verkaufsverlauf',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    entries: 'प्रविष्टियाँ',
    history: 'इतिहास',
    profile: 'प्रोफ़ाइल',
    totalSales: 'कुल बिक्री',
    monthlyGoal: 'मासिक लक्ष्य',
    recentSales: 'हाल की बिक्री',
    newSale: 'नई बिक्री',
    sellers: 'विक्रेता',
    management: 'प्रबंधन',
    preferences: 'प्राथमिकताएं',
    darkMode: 'डार्क मोड',
    language: 'भाषा',
    privacySettings: 'गोपनीयता सेटिंग्स',
    termsOfService: 'सेवा की शर्तें',
    deleteAccount: 'खाता हटाएं',
    logout: 'लॉग आउट',
    adminProfile: 'एडमिन प्रोफ़ाइल',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    stores: 'स्टोर',
    manageRetail: 'रिटेल स्थानों का प्रबंधन करें',
    staffPermissions: 'स्टाफ और टीम अनुमतियां',
    onTrack: 'ट्रैक पर',
    behind: 'पीछे',
    completed: 'पूरा हुआ',
    amount: 'राशि',
    paymentMethod: 'भुगतान विधि',
    seller: 'विक्रेता',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    removeSeller: 'विक्रेता को हटाएं',
    editSeller: 'विक्रेता को संपादित करें',
    newSeller: 'नया विक्रेता',
    sellerName: 'विक्रेता का नाम',
    contactPhone: 'संपर्क/फ़ोन',
    monthlySalesGoal: 'मासिक बिक्री लक्ष्य',
    observations: 'अवलोकन',
    changePhoto: 'फोटो बदलें',
    allSellers: 'सभी विक्रेता',
    activeSellers: 'सक्रिय विक्रेता',
    searchSellers: 'विक्रेता खोजें...',
    noSalesYet: 'अभी तक कोई बिक्री दर्ज नहीं की गई।',
    viewAll: 'सभी देखें',
    today: 'आज',
    yesterday: 'कल',
    thisMonth: 'इस महीने',
    lastMonth: 'पिछले महीने',
    day: 'दिन',
    week: 'सप्ताह',
    month: 'महीना',
    custom: 'कस्टम',
    selectDate: 'तारीख चुनें',
    selectWeek: 'सप्ताह चुनें',
    selectMonth: 'महीना चुनें',
    date: 'तारीख',
    time: 'समय',
    salesTrend: 'बिक्री का रुझान',
    revenueByDay: 'दिन के अनुसार राजस्व',
    physicalStore: 'भौतिक स्टोर',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'बिक्री चैनल',
    performanceByPlatform: 'प्लेटफ़ॉर्म के अनुसार प्रदर्शन',
    total: 'कुल',
    remaining: 'शेष',
    currentSales: 'वर्तमान बिक्री',
    recentGoalProgress: 'हालिया लक्ष्य प्रगति',
    ofTargetReached: 'लक्ष्य तक पहुँच गया',
    monthlyProgress: 'मासिक प्रगति',
    totalsByPaymentMethod: 'भुगतान विधि द्वारा कुल',
    dailyView: 'दैनिक दृश्य',
    sellerPerformance: 'विक्रेता प्रदर्शन',
    grandTotal: 'कुल योग',
    salesToday: 'आज की बिक्री',
    cash: 'नकद',
    credit: 'क्रेडिट',
    debit: 'डेबिट',
    pix: 'PIX',
    last7Days: 'पिछले 7 दिन',
    last30Days: 'पिछले 30 दिन',
    goalResult: 'लक्ष्य परिणाम',
    share: 'साझा करें',
    teamMembers: 'टीम के सदस्य',
    addNew: 'नया जोड़ें',
    noSellersYet: 'अभी तक कोई विक्रेता पंजीकृत नहीं है।',
    registerFirstSeller: 'पहला विक्रेता पंजीकृत करें',
    goal: 'लक्ष्य',
    confirmRemoveSeller: 'क्या आप वाकई इस विक्रेता को हटाना चाहते हैं?',
    fullName: 'पूरा नाम',
    phonePlaceholder: '+91 00000 00000',
    observationsPlaceholder: 'प्रदर्शन, शेड्यूल आदि के बारे में नोट्स जोड़ें।',
    aiAssistant: 'AI सहायक',
    scanReceipt: 'फॉर्म भरने के लिए रसीद स्कैन करें',
    uploadSpreadsheet: 'स्प्रेडशीट अपलोड करें',
    extractingData: 'डेटा निकाला जा रहा है...',
    extractedSales: 'निकाली गई बिक्री',
    registerSales: 'बिक्री दर्ज करें',
    selectSalesToRegister: 'दर्ज करने के लिए बिक्री चुनें',
    value: 'मूल्य',
    origin: 'उत्पत्ति',
    noSalesFound: 'कोई बिक्री नहीं मिली',
    selectAll: 'सभी चुनें',
    deselectAll: 'सभी को अचयनित करें',
    analyzing: 'विश्लेषण कर रहा है...',
    scan: 'स्कैन',
    saleDetails: 'बिक्री विवरण',
    saving: 'सहेज रहा है...',
    confirmSale: 'बिक्री की पुष्टि करें',
    achievementUnlocked: 'उपलब्धि अनलॉक!',
    welcomeMessage: 'पेशेवर बिक्री प्रदर्शन डैशबोर्ड',
    signInDescription: 'अपने डैशबोर्ड तक पहुँचने के लिए साइन इन करें।',
    signInWithGoogle: 'Google के साथ साइन इन करें',
    authAgreement: 'साइन इन करके, आप हमारी शर्तों से सहमत होते हैं।',
    applicationError: 'एप्लिकेशन त्रुटि',
    somethingWentWrong: 'कुछ गलत हो गया।',
    permissionDenied: 'अनुमति नहीं है।',
    reloadApplication: 'एप्लिकेशन को फिर से लोड करें',
    mon: 'सोम',
    tue: 'मंगल',
    wed: 'बुध',
    thu: 'गुरु',
    fri: 'शुक्र',
    sat: 'शनि',
    sun: 'रवि',
    w1: 'स1',
    w2: 'स2',
    w3: 'स3',
    w4: 'स4',
    releases: 'रिलीज',
    bleed: 'निकासी',
    reinforcement: 'सुदृढीकरण',
    confirmMovement: 'आंदोलน की पुष्टि करें',
    addNotes: 'नोट/सिक्के जोड़ें',
    observation: 'अवलोकन',
    confirm: 'पुष्टि करें',
    paymentMethodDetail: 'भुगतान विधि विवरण',
    netCash: 'शुद्ध नकद',
    totalSalesByMethod: 'कुल बिक्री',
    totalSangrias: 'कुल निकासी',
    totalReforcos: 'कुल सुदृढीकरण',
    calculatedCash: 'परिकलित नकद',
    summary: 'सारांश',
    dailyReport: 'दैनिक रिपोर्ट',
    closing: 'समापन',
    downloadPDF: 'पीडीएफ डाउनलोड करें',
    salesSummary: 'बिक्री सारांश',
    grossSales: 'कुल बिक्री',
    discounts: 'छूट',
    netTotal: 'शुद्ध कुल',
    transactions: 'लेन-देन',
    averageTicket: 'औसत टिकट',
    cashReconciliation: 'नकद मिलान',
    cashReconciledSuccess: 'नकद का सफलतापूर्वक मिलान किया गया। कोई विसंगति नहीं मिली।',
    dailyGoal: 'दैनिक लक्ष्य',
    achieved: 'प्राप्त',
    onlyMissing: 'केवल कमी',
    goalMet: 'लक्ष्य पूरा हुआ!',
    exceededBy: 'से अधिक',
    goalOfTheDay: 'दिन का लक्ष्य',
    reportGeneratedAutomatically: 'रिपोर्ट स्वचालित रूप से उत्पन्न',
    ofReport: 'रिपोर्ट का',
    of: 'का',
    card: 'कार्ड',
    debitCredit: 'डेबिट/क्रेडिट',
    pdf: 'पीडीएफ',
    unknown: 'अज्ञात',
    motivationalImage: 'प्रेरक छवि',
    profileImage: 'प्रोफ़ाइल छवि',
    user: 'उपयोगकर्ता',
    email: 'ईमेल',
    emailPlaceholder: 'seller@example.com',
    goalPlaceholder: '5000',
    preview: 'पूर्वावलोकन',
    copiedToClipboard: 'क्लिपबोर्ड पर कॉपी किया गया!',
    detail: 'विवरण',
    sale: 'बिक्री',
    vs: 'बनाम',
    id: 'आईडी',
    loadingData: 'डेटा लोड हो रहा है...',
    amountPlaceholder: '0.00',
    salesHistory: 'बिक्री इतिहास',
    paymentLink: 'भुगतान लिंक',
    exchangeVoucher: 'एक्सचेंज वाउचर',
    'payment-link': 'भुगतान लिंक',
    'exchange-voucher': 'एक्सचेंज वाउचर',
    totalAmount: 'कुल राशि',
    addPaymentMethod: 'भुगतान विधि जोड़ें',
    remainingAmount: 'शेष राशि',
    totalPaid: 'कुल भुगतान',
    salesBySource: 'स्रोत द्वारा बिक्री',
    spreadsheet: 'स्प्रेडशीट',
    upload: 'अपलोड',
  },
  ru: {
    dashboard: 'Панель',
    entries: 'Записи',
    history: 'История',
    profile: 'Профиль',
    totalSales: 'Всего продаж',
    monthlyGoal: 'Месячная цель',
    recentSales: 'Последние продажи',
    newSale: 'Новая продажа',
    sellers: 'Продавцы',
    management: 'Управление',
    preferences: 'Настройки',
    darkMode: 'Темный режим',
    language: 'Язык',
    privacySettings: 'Конфиденциальность',
    termsOfService: 'Условия использования',
    deleteAccount: 'Удалить аккаунт',
    logout: 'Выйти',
    adminProfile: 'Профиль админа',
    editProfile: 'Редактировать профиль',
    stores: 'Магазины',
    manageRetail: 'Управление точками',
    staffPermissions: 'Персонал и права',
    onTrack: 'В графике',
    behind: 'Отстает',
    completed: 'Завершено',
    amount: 'Сумма',
    paymentMethod: 'Способ оплаты',
    seller: 'Продавец',
    save: 'Сохранить',
    cancel: 'Отмена',
    removeSeller: 'Удалить продавца',
    editSeller: 'Редактировать продавца',
    newSeller: 'Новый продавец',
    sellerName: 'Имя продавца',
    contactPhone: 'Контакт/Телефон',
    monthlySalesGoal: 'Месячный план продаж',
    observations: 'Примечания',
    changePhoto: 'Изменить фото',
    allSellers: 'Все продавцы',
    activeSellers: 'Активные продавцы',
    searchSellers: 'Поиск продавцов...',
    noSalesYet: 'Продаж пока нет.',
    viewAll: 'Показать все',
    today: 'Сегодня',
    yesterday: 'Вчера',
    thisMonth: 'В этом месяце',
    lastMonth: 'В прошлом месяце',
    day: 'День',
    week: 'Неделя',
    month: 'Месяц',
    custom: 'Пользовательский',
    selectDate: 'Выбрать дату',
    selectWeek: 'Выбрать неделю',
    selectMonth: 'Выбрать месяц',
    salesTrend: 'Тенденция продаж',
    revenueByDay: 'Выручка по дням',
    physicalStore: 'Магазин',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'Каналы продаж',
    performanceByPlatform: 'Эффективность платформ',
    total: 'Всего',
    remaining: 'Осталось',
    currentSales: 'Текущие продажи',
    recentGoalProgress: 'Прогресс целей',
    ofTargetReached: 'цели достигнуто',
    monthlyProgress: 'Ежемесячный прогресс',
    totalsByPaymentMethod: 'Итоги по способам оплаты',
    dailyView: 'Дневной вид',
    sellerPerformance: 'Эффективность продавцов',
    grandTotal: 'Общий итог',
    salesToday: 'продаж сегодня',
    cash: 'Наличные',
    credit: 'Кредит',
    debit: 'Дебет',
    pix: 'PIX',
    last7Days: 'Последние 7 дней',
    last30Days: 'Последние 30 дней',
    goalResult: 'Результат цели',
    share: 'Поделиться',
    teamMembers: 'Члены команды',
    addNew: 'Добавить',
    noSellersYet: 'Продавцы не зарегистрированы.',
    registerFirstSeller: 'Зарегистрировать первого продавца',
    goal: 'Цель',
    confirmRemoveSeller: 'Вы уверены, что хотите удалить продавца?',
    fullName: 'Полное имя',
    phonePlaceholder: '+7 000 000-00-00',
    observationsPlaceholder: 'Примечания к работе и т.д.',
    aiAssistant: 'ИИ-помощник',
    scanReceipt: 'Сканируйте чек для автозаполнения',
    uploadSpreadsheet: 'Загрузить таблицу',
    extractingData: 'Извлечение данных...',
    extractedSales: 'Извлеченные продажи',
    registerSales: 'Зарегистрировать продажи',
    selectSalesToRegister: 'Выберите продажи для регистрации',
    date: 'Дата',
    time: 'Время',
    value: 'Значение',
    origin: 'Происхождение',
    noSalesFound: 'Продажи не найдены',
    selectAll: 'Выбрать все',
    deselectAll: 'Отменить все',
    analyzing: 'Анализ...',
    scan: 'Сканировать',
    saleDetails: 'Детали продажи',
    saving: 'Сохранение...',
    confirmSale: 'Подтвердить продажу',
    achievementUnlocked: 'Достижение разблокировано!',
    welcomeMessage: 'Профессиональная панель продаж',
    signInDescription: 'Войдите, чтобы получить доступ к панели.',
    signInWithGoogle: 'Войти через Google',
    authAgreement: 'Входя, вы соглашаетесь с условиями.',
    applicationError: 'Ошибка приложения',
    somethingWentWrong: 'Что-то пошло не так.',
    permissionDenied: 'Доступ запрещен.',
    reloadApplication: 'Перезагрузить приложение',
    mon: 'Пн',
    tue: 'Вт',
    wed: 'Ср',
    thu: 'Чт',
    fri: 'Пт',
    sat: 'Сб',
    sun: 'Вс',
    w1: 'Н1',
    w2: 'Н2',
    w3: 'Н3',
    w4: 'Н4',
    releases: 'Выпуски',
    bleed: 'Изъятие',
    reinforcement: 'Пополнение',
    confirmMovement: 'Подтвердить движение',
    addNotes: 'Добавить купюры/монеты',
    observation: 'Наблюдение',
    confirm: 'Подтвердить',
    paymentMethodDetail: 'Детали способа оплаты',
    netCash: 'Чистая наличность',
    totalSalesByMethod: 'Общие продажи',
    totalSangrias: 'Всего изъятий',
    totalReforcos: 'Всего пополнений',
    calculatedCash: 'Расчетная наличность',
    summary: 'Резюме',
    dailyReport: 'Ежедневный отчет',
    closing: 'Закрытие',
    downloadPDF: 'Скачать PDF',
    salesSummary: 'Отчет по продажам',
    grossSales: 'Валовые продажи',
    discounts: 'Скидки',
    netTotal: 'Чистый итог',
    transactions: 'Транзакции',
    averageTicket: 'Средний чек',
    cashReconciliation: 'Сверка наличности',
    cashReconciledSuccess: 'Наличность успешно сверена. Расхождений не обнаружено.',
    dailyGoal: 'Ежедневная цель',
    achieved: 'Достигнуто',
    onlyMissing: 'Осталось всего',
    goalMet: 'Цель достигнута!',
    exceededBy: 'Превышено на',
    goalOfTheDay: 'Цель на день',
    reportGeneratedAutomatically: 'Отчет сформирован автоматически',
    ofReport: 'отчета',
    of: 'от',
    card: 'Карта',
    debitCredit: 'Дебет/Кредит',
    pdf: 'PDF',
    unknown: 'Неизвестно',
    motivationalImage: 'Мотивационное изображение',
    profileImage: 'Изображение профиля',
    user: 'Пользователь',
    email: 'Электронная почта',
    emailPlaceholder: 'seller@example.com',
    goalPlaceholder: '5000',
    preview: 'Предпросмотр',
    copiedToClipboard: 'Скопировано в буфер обмена!',
    detail: 'Детали',
    sale: 'Продажа',
    vs: 'против',
    id: 'ID',
    loadingData: 'Загрузка данных...',
    amountPlaceholder: '0.00',
    salesHistory: 'История продаж',
    paymentLink: 'Ссылка на оплату',
    exchangeVoucher: 'Обменный ваучер',
    'payment-link': 'Ссылка на оплату',
    'exchange-voucher': 'Обменный ваучер',
    totalAmount: 'Итоговая сумма',
    addPaymentMethod: 'Добавить способ оплаты',
    remainingAmount: 'Оставшаяся сумма',
    totalPaid: 'Всего оплачено',
    salesBySource: 'Продажи по источнику',
    spreadsheet: 'Таблица',
    upload: 'Загрузить',
  },
  ja: {
    dashboard: 'ダッシュボード',
    entries: '入力',
    history: '履歴',
    profile: 'プロフィール',
    totalSales: '総売上',
    monthlyGoal: '月間目標',
    recentSales: '最近の売上',
    newSale: '新規売上',
    sellers: '販売員',
    management: '管理',
    preferences: '設定',
    darkMode: 'ダークモード',
    language: '言語',
    privacySettings: 'プライバシー設定',
    termsOfService: '利用規約',
    deleteAccount: 'アカウント削除',
    logout: 'ログアウト',
    adminProfile: '管理者プロフィール',
    editProfile: 'プロフィール編集',
    stores: '店舗',
    manageRetail: '小売拠点の管理',
    staffPermissions: 'スタッフと権限',
    onTrack: '順調',
    behind: '遅延',
    completed: '完了',
    amount: '金額',
    paymentMethod: '支払い方法',
    seller: '販売員',
    save: '保存',
    cancel: 'キャンセル',
    removeSeller: '販売員を削除',
    editSeller: '販売員を編集',
    newSeller: '新規販売員',
    sellerName: '販売員名',
    contactPhone: '連絡先/電話',
    monthlySalesGoal: '月間売上目標',
    observations: '備考',
    changePhoto: '写真を変更',
    allSellers: '全販売員',
    activeSellers: 'アクティブな販売員',
    searchSellers: '販売員を検索...',
    noSalesYet: '売上はまだありません。',
    viewAll: 'すべて表示',
    today: '今日',
    yesterday: '昨日',
    thisMonth: '今月',
    lastMonth: '先月',
    day: '日',
    week: '週',
    month: '月',
    custom: 'カスタム',
    selectDate: '日付を選択',
    selectWeek: '週を選択',
    selectMonth: '月を選択',
    date: '日付',
    time: '時間',
    salesTrend: '売上トレンド',
    revenueByDay: '日別収益',
    physicalStore: '実店舗',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: '販売チャネル',
    performanceByPlatform: 'プラットフォーム別パフォーマンス',
    total: '合計',
    remaining: '残り',
    currentSales: '現在の売上',
    recentGoalProgress: '最近の目標進捗',
    ofTargetReached: 'の目標達成',
    monthlyProgress: '月間進捗',
    totalsByPaymentMethod: '支払い方法別合計',
    dailyView: '日別表示',
    sellerPerformance: '販売員パフォーマンス',
    grandTotal: '総合計',
    salesToday: '今日の売上',
    cash: '現金',
    credit: 'クレジット',
    debit: 'デビット',
    pix: 'PIX',
    last7Days: '過去7日間',
    last30Days: '過去30日間',
    goalResult: '目標結果',
    share: '共有',
    teamMembers: 'チームメンバー',
    addNew: '新規追加',
    noSellersYet: '販売員が登録されていません。',
    registerFirstSeller: '最初の販売員を登録',
    goal: '目標',
    confirmRemoveSeller: 'この販売員を削除してもよろしいですか？',
    fullName: 'フルネーム',
    phonePlaceholder: '000-0000-0000',
    observationsPlaceholder: 'パフォーマンスやスケジュールなどのメモを追加',
    aiAssistant: 'AIアシスタント',
    scanReceipt: 'レシートをスキャンして自動入力',
    uploadSpreadsheet: 'スプレッドシートをアップロード',
    extractingData: 'データを抽出中...',
    extractedSales: '抽出された売上',
    registerSales: '売上を登録',
    selectSalesToRegister: '登録する売上を選択',
    value: '金額',
    origin: '発生元',
    noSalesFound: '売上が見つかりません',
    selectAll: 'すべて選択',
    deselectAll: 'すべて選択解除',
    analyzing: '分析中...',
    scan: 'スキャン',
    saleDetails: '売上詳細',
    saving: '保存中...',
    confirmSale: '売上を確定',
    achievementUnlocked: '実績解除！',
    welcomeMessage: 'プロフェッショナル売上ダッシュボード',
    signInDescription: 'ダッシュボードにアクセスするにはサインインしてください。',
    signInWithGoogle: 'Googleでサインイン',
    authAgreement: 'サインインすることで、利用規約とプライバシーポリシーに同意したことになります。',
    applicationError: 'アプリケーションエラー',
    somethingWentWrong: '問題が発生しました。',
    permissionDenied: '権限がありません。',
    reloadApplication: 'アプリを再読み込み',
    mon: '月',
    tue: '火',
    wed: '水',
    thu: '木',
    fri: '金',
    sat: '土',
    sun: '日',
    w1: '第1週',
    w2: '第2週',
    w3: '第3週',
    w4: '第4週',
    releases: 'リリース',
    bleed: '出金',
    reinforcement: '入金',
    confirmMovement: '移動を確定する',
    addNotes: '紙幣/硬貨を追加',
    observation: '備考',
    confirm: '確定',
    paymentMethodDetail: '支払い方法の詳細',
    netCash: '純現金',
    totalSalesByMethod: '総売上',
    totalSangrias: '出金合計',
    totalReforcos: '入金合計',
    calculatedCash: '計算上の現金',
    summary: '要約',
    dailyReport: '日報',
    closing: '締め切り',
    downloadPDF: 'PDFをダウンロード',
    salesSummary: '売上要約',
    grossSales: '総売上高',
    discounts: '割引',
    netTotal: '純計',
    transactions: '取引数',
    averageTicket: '客単価',
    cashReconciliation: '現金照合',
    cashReconciledSuccess: '現金の照合が完了しました。不一致はありません。',
    dailyGoal: '今日の目標',
    achieved: '達成',
    onlyMissing: '残りわずか',
    goalMet: '目標達成！',
    exceededBy: '超過額',
    goalOfTheDay: '今日の目標',
    reportGeneratedAutomatically: 'レポートは自動的に生成されました',
    ofReport: 'レポートの',
    of: 'の',
    card: 'カード',
    debitCredit: 'デビット/クレジット',
    pdf: 'PDF',
    unknown: '不明',
    motivationalImage: 'モチベーション画像',
    profileImage: 'プロフィール画像',
    user: 'ユーザー',
    email: 'メール',
    emailPlaceholder: 'seller@example.com',
    goalPlaceholder: '5000',
    preview: 'プレビュー',
    copiedToClipboard: 'クリップボードにコピーされました！',
    detail: '詳細',
    sale: '販売',
    vs: '対',
    id: 'ID',
    loadingData: 'データを読み込んでいます...',
    amountPlaceholder: '0.00',
    salesHistory: '販売履歴',
    paymentLink: '支払いリンク',
    exchangeVoucher: '交換バウチャー',
    'payment-link': '支払いリンク',
    'exchange-voucher': '交換バウチャー',
    totalAmount: '合計金額',
    addPaymentMethod: '支払い方法を追加',
    remainingAmount: '残額',
    totalPaid: '支払い合計',
    salesBySource: 'ソース別の売上',
    spreadsheet: 'スプレッドシート',
    upload: 'アップロード',
  },
  zh: {
    dashboard: '仪表板',
    entries: '条目',
    history: '历史',
    profile: '个人资料',
    totalSales: '总销售额',
    monthlyGoal: '每月目标',
    recentSales: '最近销售',
    newSale: '新增销售',
    sellers: '销售员',
    management: '管理',
    preferences: '首选项',
    darkMode: '深色模式',
    language: '语言',
    privacySettings: '隐私设置',
    termsOfService: '服务条款',
    deleteAccount: '删除账户',
    logout: '退出登录',
    adminProfile: '管理员资料',
    editProfile: '编辑资料',
    stores: '商店',
    manageRetail: '管理零售地点',
    staffPermissions: '员工和团队权限',
    onTrack: '正常',
    behind: '落后',
    completed: '已完成',
    amount: '金额',
    paymentMethod: '付款方式',
    seller: '销售员',
    save: '保存',
    cancel: '取消',
    removeSeller: '移除销售员',
    editSeller: '编辑销售员',
    newSeller: '新增销售员',
    sellerName: '销售员姓名',
    contactPhone: '联系方式/电话',
    monthlySalesGoal: '每月销售目标',
    observations: '备注',
    changePhoto: '更换照片',
    allSellers: '所有销售员',
    activeSellers: '活跃销售员',
    searchSellers: '搜索销售员...',
    noSalesYet: '暂无销售记录。',
    viewAll: '查看全部',
    today: '今天',
    yesterday: '昨天',
    thisMonth: '本月',
    lastMonth: '上月',
    day: '日',
    week: '周',
    month: '月',
    custom: '自定义',
    selectDate: '选择日期',
    selectWeek: '选择周',
    selectMonth: '选择月',
    salesTrend: '销售趋势',
    revenueByDay: '每日收入',
    physicalStore: '实体店',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: '销售渠道',
    performanceByPlatform: '平台绩效',
    total: '总计',
    remaining: '剩余',
    currentSales: '当前销售',
    recentGoalProgress: '近期目标进度',
    ofTargetReached: '目标已达成',
    monthlyProgress: '月度进度',
    totalsByPaymentMethod: '按付款方式统计',
    dailyView: '每日视图',
    sellerPerformance: '销售员绩效',
    grandTotal: '总计',
    salesToday: '今日销售',
    cash: '现金',
    credit: '信用卡',
    debit: '借记卡',
    pix: 'PIX',
    last7Days: '最近7天',
    last30Days: '最近30天',
    goalResult: '目标结果',
    share: '分享',
    teamMembers: '团队成员',
    addNew: '新增',
    noSellersYet: '暂无销售员。',
    registerFirstSeller: '注册首位销售员',
    goal: '目标',
    confirmRemoveSeller: '确定要移除该销售员吗？',
    fullName: '全名',
    phonePlaceholder: '000-0000-0000',
    observationsPlaceholder: '添加关于绩效、排班等的备注',
    aiAssistant: 'AI 助手',
    scanReceipt: '扫描收据自动填写',
    uploadSpreadsheet: '上传电子表格',
    extractingData: '正在提取数据...',
    extractedSales: '提取的销售额',
    registerSales: '登记销售额',
    selectSalesToRegister: '选择要登记的销售额',
    date: '日期',
    time: '时间',
    value: '金额',
    origin: '来源',
    noSalesFound: '未找到销售额',
    selectAll: '全选',
    deselectAll: '全不选',
    analyzing: '分析中...',
    scan: '扫描',
    saleDetails: '销售详情',
    saving: '保存中...',
    confirmSale: '确认销售',
    achievementUnlocked: '成就已解锁！',
    welcomeMessage: '专业销售绩效仪表板',
    signInDescription: '登录以访问您的仪表板。',
    signInWithGoogle: '使用 Google 登录',
    authAgreement: '登录即表示您同意我们的条款。',
    applicationError: '应用错误',
    somethingWentWrong: '出错了。',
    permissionDenied: '无权限。',
    reloadApplication: '重新加载应用',
    mon: '周一',
    tue: '周二',
    wed: '周三',
    thu: '周四',
    fri: '周五',
    sat: '周六',
    sun: '周日',
    w1: '第一周',
    w2: '第二周',
    w3: '第三周',
    w4: '第四周',
    releases: '发布',
    bleed: '支出',
    reinforcement: '补给',
    confirmMovement: '确认变动',
    addNotes: '添加纸币/硬币',
    observation: '备注',
    confirm: '确认',
    paymentMethodDetail: '付款方式详情',
    netCash: '净现金',
    totalSalesByMethod: '总销售额',
    totalSangrias: '总支出',
    totalReforcos: '总补给',
    calculatedCash: '计算现金',
    summary: '摘要',
    dailyReport: '日报',
    closing: '结账',
    downloadPDF: '下载 PDF',
    salesSummary: '销售摘要',
    grossSales: '总销售额',
    discounts: '折扣',
    netTotal: '净总计',
    transactions: '交易次数',
    averageTicket: '平均客单价',
    cashReconciliation: '现金对账',
    cashReconciledSuccess: '现金对账成功。未发现差异。',
    dailyGoal: '每日目标',
    achieved: '已达成',
    onlyMissing: '仅差',
    goalMet: '目标达成！',
    exceededBy: '超出',
    goalOfTheDay: '今日目标',
    reportGeneratedAutomatically: '报告自动生成',
    ofReport: '报告',
    of: '的',
    card: '卡',
    debitCredit: '借记/信用卡',
    pdf: 'PDF',
    unknown: '未知',
    motivationalImage: '励志图片',
    profileImage: '个人资料图片',
    user: '用户',
    email: '电子邮件',
    emailPlaceholder: 'seller@example.com',
    goalPlaceholder: '5000',
    preview: '预览',
    copiedToClipboard: '已复制到剪贴板！',
    detail: '详情',
    sale: '销售',
    vs: '对比',
    id: 'ID',
    loadingData: '正在加载数据...',
    amountPlaceholder: '0.00',
    salesHistory: '销售历史',
    paymentLink: '支付链接',
    exchangeVoucher: '换货券',
    'payment-link': '支付链接',
    'exchange-voucher': '换货券',
    totalAmount: '总金额',
    addPaymentMethod: '添加付款方式',
    remainingAmount: '剩余金额',
    totalPaid: '总支付额',
    salesBySource: '按来源分类的销售',
    spreadsheet: '电子表格',
    upload: '上传',
  },
  ko: {
    dashboard: '대시보드',
    entries: '입력',
    history: '내역',
    profile: '프로필',
    totalSales: '총 매출',
    monthlyGoal: '월간 목표',
    recentSales: '최근 매출',
    newSale: '신규 매출',
    sellers: '판매원',
    management: '관리',
    preferences: '설정',
    darkMode: '다크 모드',
    language: '언어',
    privacySettings: '개인정보 설정',
    termsOfService: '서비스 약관',
    deleteAccount: '계정 삭제',
    logout: '로그아웃',
    adminProfile: '관리자 프로필',
    editProfile: '프로필 수정',
    stores: '매장',
    manageRetail: '소매 위치 관리',
    staffPermissions: '직원 및 팀 권한',
    onTrack: '정상',
    behind: '지연',
    completed: '완료',
    amount: '금액',
    paymentMethod: '결제 방법',
    seller: '판매원',
    save: '저장',
    cancel: '취소',
    removeSeller: '판매원 삭제',
    editSeller: '판매원 수정',
    newSeller: '신규 판매원',
    sellerName: '판매원 이름',
    contactPhone: '연락처/전화번호',
    monthlySalesGoal: '월간 매출 목표',
    observations: '비고',
    changePhoto: '사진 변경',
    allSellers: '모든 판매원',
    activeSellers: '활성 판매원',
    searchSellers: '판매원 검색...',
    noSalesYet: '매출 기록이 없습니다.',
    viewAll: '모두 보기',
    today: '오늘',
    yesterday: '어제',
    thisMonth: '이번 달',
    lastMonth: '지난 달',
    day: '일',
    week: '주',
    month: '월',
    custom: '사용자 정의',
    selectDate: '날짜 선택',
    selectWeek: '주 선택',
    selectMonth: '월 선택',
    salesTrend: '매출 트렌드',
    revenueByDay: '일별 수익',
    physicalStore: '오프라인 매장',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: '판매 채널',
    performanceByPlatform: '플랫폼별 성과',
    total: '합계',
    remaining: '남음',
    currentSales: '현재 매출',
    recentGoalProgress: '최근 목표 진행 상황',
    ofTargetReached: '목표 달성',
    monthlyProgress: '월간 진행률',
    totalsByPaymentMethod: '결제 방법별 합계',
    dailyView: '일별 보기',
    sellerPerformance: '판매원 성과',
    grandTotal: '총합계',
    salesToday: '오늘의 판매',
    cash: '현금',
    credit: '신용카드',
    debit: '직불카드',
    pix: 'PIX',
    last7Days: '최근 7일',
    last30Days: '최근 30일',
    goalResult: '목표 결과',
    share: '공유',
    teamMembers: '팀원',
    addNew: '새로 추가',
    noSellersYet: '등록된 판매원이 없습니다.',
    registerFirstSeller: '첫 판매원 등록',
    goal: '목표',
    confirmRemoveSeller: '이 판매원을 삭제하시겠습니까?',
    fullName: '성함',
    phonePlaceholder: '010-0000-0000',
    observationsPlaceholder: '성과, 일정 등에 대한 메모 추가',
    aiAssistant: 'AI 어시스턴트',
    scanReceipt: '영수증을 스캔하여 양식 자동 채우기',
    uploadSpreadsheet: '스프레드시트 업로드',
    extractingData: '데이터 추출 중...',
    extractedSales: '추출된 매출',
    registerSales: '매출 등록',
    selectSalesToRegister: '등록할 매출 선택',
    date: '날짜',
    time: '시간',
    value: '금액',
    origin: '출처',
    noSalesFound: '매출을 찾을 수 없음',
    selectAll: '모두 선택',
    deselectAll: '모두 선택 해제',
    analyzing: '분석 중...',
    scan: '스캔',
    saleDetails: '판매 상세 정보',
    saving: '저장 중...',
    confirmSale: '판매 확인',
    achievementUnlocked: '업적 달성!',
    welcomeMessage: '전문 판매 성과 대시보드',
    signInDescription: '대시보드에 액세스하려면 로그인하세요.',
    signInWithGoogle: 'Google로 로그인',
    authAgreement: '로그인하면 약관에 동의하는 것으로 간주됩니다.',
    applicationError: '애플리케이션 오류',
    somethingWentWrong: '문제가 발생했습니다.',
    permissionDenied: '권한이 없습니다.',
    reloadApplication: '앱 다시 로드',
    mon: '월',
    tue: '화',
    wed: '수',
    thu: '목',
    fri: '금',
    sat: '토',
    sun: '일',
    w1: '1주',
    w2: '2주',
    w3: '3주',
    w4: '4주',
    releases: '릴리스',
    bleed: '출금',
    reinforcement: '입금',
    confirmMovement: '변동 확인',
    addNotes: '지폐/동전 추가',
    observation: '비고',
    confirm: '확인',
    paymentMethodDetail: '결제 방법 상세',
    netCash: '순 현금',
    totalSalesByMethod: '총 매출',
    totalSangrias: '총 출금',
    totalReforcos: '총 입금',
    calculatedCash: '계산된 현금',
    summary: '요약',
    dailyReport: '일일 보고서',
    closing: '마감',
    downloadPDF: 'PDF 다운로드',
    salesSummary: '판매 요약',
    grossSales: '총 매출',
    discounts: '할인',
    netTotal: '순 합계',
    transactions: '거래 건수',
    averageTicket: '평균 객단가',
    cashReconciliation: '현금 정산',
    cashReconciledSuccess: '현금 정산이 성공적으로 완료되었습니다. 불일치가 없습니다.',
    dailyGoal: '일일 목표',
    achieved: '달성',
    onlyMissing: '남은 금액',
    goalMet: '목표 달성!',
    exceededBy: '초과액',
    goalOfTheDay: '오늘의 목표',
    reportGeneratedAutomatically: '보고서가 자동으로 생성되었습니다',
    ofReport: '보고서',
    of: '의',
    card: '카드',
    debitCredit: '직불/신용',
    pdf: 'PDF',
    unknown: '알 수 없음',
    motivationalImage: '동기 부여 이미지',
    profileImage: '프로필 이미지',
    user: '사용자',
    email: '이메일',
    emailPlaceholder: 'seller@example.com',
    goalPlaceholder: '5000',
    preview: '미리보기',
    copiedToClipboard: '클립보드에 복사되었습니다!',
    detail: '상세',
    sale: '판매',
    vs: '대',
    id: 'ID',
    loadingData: '데이터를 불러오는 중...',
    amountPlaceholder: '0.00',
    salesHistory: '판매 내역',
    paymentLink: '결제 링크',
    exchangeVoucher: '교환권',
    'payment-link': '결제 링크',
    'exchange-voucher': '교환권',
    totalAmount: '총액',
    addPaymentMethod: '결제 방법 추가',
    remainingAmount: '남은 금액',
    totalPaid: '총 결제액',
    salesBySource: '출처별 판매',
    spreadsheet: '스프레드시트',
    upload: '업로드',
  },
  th: {
    dashboard: 'แดชบอร์ด',
    entries: 'รายการ',
    history: 'ประวัติ',
    profile: 'โปรไฟล์',
    totalSales: 'ยอดขายรวม',
    monthlyGoal: 'เป้าหมายรายเดือน',
    recentSales: 'ยอดขายล่าสุด',
    newSale: 'เพิ่มยอดขาย',
    sellers: 'พนักงานขาย',
    management: 'การจัดการ',
    preferences: 'การตั้งค่า',
    darkMode: 'โหมดมืด',
    language: 'ภาษา',
    privacySettings: 'การตั้งค่าความเป็นส่วนตัว',
    termsOfService: 'ข้อกำหนดการให้บริการ',
    deleteAccount: 'ลบบัญชี',
    logout: 'ออกจากระบบ',
    adminProfile: 'โปรไฟล์ผู้ดูแลระบบ',
    editProfile: 'แก้ไขโปรไฟล์',
    stores: 'ร้านค้า',
    manageRetail: 'จัดการสถานที่ค้าปลีก',
    staffPermissions: 'พนักงานและสิทธิ์ทีม',
    onTrack: 'ตามแผน',
    behind: 'ล่าช้า',
    completed: 'เสร็จสมบูรณ์',
    amount: 'จำนวนเงิน',
    paymentMethod: 'วิธีการชำระเงิน',
    seller: 'พนักงานขาย',
    save: 'บันทึก',
    cancel: 'ยกเลิก',
    removeSeller: 'ลบพนักงานขาย',
    editSeller: 'แก้ไขพนักงานขาย',
    newSeller: 'พนักงานขายใหม่',
    sellerName: 'ชื่อพนักงานขาย',
    contactPhone: 'ติดต่อ/โทรศัพท์',
    monthlySalesGoal: 'เป้าหมายการขายรายเดือน',
    observations: 'หมายเหตุ',
    changePhoto: 'เปลี่ยนรูปภาพ',
    allSellers: 'พนักงานขายทั้งหมด',
    activeSellers: 'พนักงานขายที่ใช้งานอยู่',
    searchSellers: 'ค้นหาพนักงานขาย...',
    noSalesYet: 'ยังไม่มีบันทึกยอดขาย',
    viewAll: 'ดูทั้งหมด',
    today: 'วันนี้',
    yesterday: 'เมื่อวาน',
    thisMonth: 'เดือนนี้',
    lastMonth: 'เดือนที่แล้ว',
    day: 'วัน',
    week: 'สัปดาห์',
    month: 'เดือน',
    custom: 'กำหนดเอง',
    selectDate: 'เลือกวันที่',
    selectWeek: 'เลือกสัปดาห์',
    selectMonth: 'เลือกเดือน',
    salesTrend: 'แนวโน้มยอดขาย',
    revenueByDay: 'รายได้ตามวัน',
    physicalStore: 'หน้าร้าน',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'ช่องทางการขาย',
    performanceByPlatform: 'ประสิทธิภาพตามแพลตฟอร์ม',
    total: 'รวม',
    remaining: 'คงเหลือ',
    currentSales: 'ยอดขายปัจจุบัน',
    recentGoalProgress: 'ความคืบหน้าเป้าหมายล่าสุด',
    ofTargetReached: 'ของเป้าหมายที่บรรลุ',
    monthlyProgress: 'ความคืบหน้ารายเดือน',
    totalsByPaymentMethod: 'ยอดรวมตามวิธีการชำระเงิน',
    dailyView: 'มุมมองรายวัน',
    sellerPerformance: 'ประสิทธิภาพพนักงานขาย',
    grandTotal: 'ยอดรวมทั้งหมด',
    salesToday: 'ยอดขายวันนี้',
    cash: 'เงินสด',
    credit: 'บัตรเครดิต',
    debit: 'บัตรเดบิต',
    pix: 'PIX',
    last7Days: '7 วันที่ผ่านมา',
    last30Days: '30 วันที่ผ่านมา',
    goalResult: 'ผลลัพธ์เป้าหมาย',
    share: 'แชร์',
    teamMembers: 'สมาชิกในทีม',
    addNew: 'เพิ่มใหม่',
    noSellersYet: 'ยังไม่มีพนักงานขายที่ลงทะเบียน',
    registerFirstSeller: 'ลงทะเบียนพนักงานขายคนแรก',
    goal: 'เป้าหมาย',
    confirmRemoveSeller: 'คุณแน่ใจหรือไม่ว่าต้องการลบพนักงานขายคนนี้?',
    fullName: 'ชื่อ-นามสกุล',
    phonePlaceholder: '081-000-0000',
    observationsPlaceholder: 'เพิ่มบันทึกเกี่ยวกับประสิทธิภาพ ตารางเวลา ฯลฯ',
    aiAssistant: 'ผู้ช่วย AI',
    scanReceipt: 'สแกนใบเสร็จเพื่อกรอกแบบฟอร์มอัตโนมัติ',
    uploadSpreadsheet: 'อัปโหลดสเปรดชีต',
    extractingData: 'กำลังดึงข้อมูล...',
    extractedSales: 'ยอดขายที่ดึงออกมา',
    registerSales: 'ลงทะเบียนยอดขาย',
    selectSalesToRegister: 'เลือกยอดขายที่จะลงทะเบียน',
    date: 'วันที่',
    time: 'เวลา',
    value: 'มูลค่า',
    origin: 'ที่มา',
    noSalesFound: 'ไม่พบยอดขาย',
    selectAll: 'เลือกทั้งหมด',
    deselectAll: 'ยกเลิกการเลือกทั้งหมด',
    analyzing: 'กำลังวิเคราะห์...',
    scan: 'สแกน',
    saleDetails: 'รายละเอียดการขาย',
    saving: 'กำลังบันทึก...',
    confirmSale: 'ยืนยันการขาย',
    achievementUnlocked: 'ปลดล็อกความสำเร็จ!',
    welcomeMessage: 'แดชบอร์ดประสิทธิภาพการขายระดับมืออาชีพ',
    signInDescription: 'ลงชื่อเข้าใช้เพื่อเข้าถึงแดชบอร์ดของคุณ',
    signInWithGoogle: 'ลงชื่อเข้าใช้ด้วย Google',
    authAgreement: 'การลงชื่อเข้าใช้แสดงว่าคุณยอมรับข้อกำหนดของเรา',
    applicationError: 'ข้อผิดพลาดของแอปพลิเคชัน',
    somethingWentWrong: 'มีบางอย่างผิดพลาด',
    permissionDenied: 'คุณไม่มีสิทธิ์',
    reloadApplication: 'โหลดแอปพลิเคชันใหม่',
    releases: 'รายการปล่อย',
    bleed: 'ถอนเงิน',
    reinforcement: 'เติมเงิน',
    mon: 'จ.',
    tue: 'อ.',
    wed: 'พ.',
    thu: 'พฤ.',
    fri: 'ศ.',
    sat: 'ส.',
    sun: 'อา.',
    w1: 'สัปดาห์ที่ 1',
    w2: 'สัปดาห์ที่ 2',
    w3: 'สัปดาห์ที่ 3',
    w4: 'สัปดาห์ที่ 4',
    confirmMovement: 'ยืนยันการเคลื่อนไหว',
    addNotes: 'เพิ่มธนบัตร/เหรียญ',
    observation: 'หมายเหตุ',
    confirm: 'ยืนยัน',
    paymentMethodDetail: 'รายละเอียดวิธีการชำระเงิน',
    netCash: 'เงินสดสุทธิ',
    totalSalesByMethod: 'ยอดขายรวม',
    totalSangrias: 'ยอดถอนรวม',
    totalReforcos: 'ยอดเติมรวม',
    calculatedCash: 'เงินสดที่คำนวณได้',
    summary: 'สรุป',
    dailyReport: 'รายงานประจำวัน',
    closing: 'การปิดยอด',
    downloadPDF: 'ดาวน์โหลด PDF',
    salesSummary: 'สรุปยอดขาย',
    grossSales: 'ยอดขายรวม',
    discounts: 'ส่วนลด',
    netTotal: 'ยอดรวมสุทธิ',
    transactions: 'จำนวนรายการ',
    averageTicket: 'ยอดขายเฉลี่ยต่อบิล',
    cashReconciliation: 'การกระทบยอดเงินสด',
    cashReconciledSuccess: 'กระทบยอดเงินสดสำเร็จ ไม่พบส่วนต่าง',
    dailyGoal: 'เป้าหมายรายวัน',
    achieved: 'บรรลุแล้ว',
    onlyMissing: 'ขาดอีกเพียง',
    goalMet: 'บรรลุเป้าหมาย!',
    exceededBy: 'เกินไป',
    goalOfTheDay: 'เป้าหมายของวัน',
    reportGeneratedAutomatically: 'รายงานสร้างขึ้นโดยอัตโนมัติ',
    ofReport: 'ของรายงาน',
    of: 'ของ',
    card: 'บัตร',
    debitCredit: 'เดบิต/เครดิต',
    pdf: 'PDF',
    unknown: 'ไม่ทราบ',
    motivationalImage: 'รูปภาพสร้างแรงบันดาลใจ',
    profileImage: 'รูปโปรไฟล์',
    user: 'ผู้ใช้',
    email: 'อีเมล',
    emailPlaceholder: 'seller@example.com',
    goalPlaceholder: '5000',
    preview: 'ตัวอย่าง',
    copiedToClipboard: 'คัดลอกไปยังคลิปบอร์ดแล้ว!',
    detail: 'รายละเอียด',
    sale: 'การขาย',
    vs: 'เทียบกับ',
    id: 'ID',
    loadingData: 'กำลังโหลดข้อมูล...',
    amountPlaceholder: '0.00',
    salesHistory: 'ประวัติการขาย',
    paymentLink: 'ลิงก์ชำระเงิน',
    exchangeVoucher: 'บัตรแลกเปลี่ยน',
    'payment-link': 'ลิงก์ชำระเงิน',
    'exchange-voucher': 'บัตรแลกเปลี่ยน',
    totalAmount: 'จำนวนเงินรวม',
    addPaymentMethod: 'เพิ่มวิธีการชำระเงิน',
    remainingAmount: 'จำนวนเงินคงเหลือ',
    totalPaid: 'ยอดชำระทั้งหมด',
    salesBySource: 'ยอดขายตามที่มา',
    spreadsheet: 'สเปรดชีต',
    upload: 'อัปโหลด',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  t: (key: string) => string;
  formatCurrency: (amount: number) => string;
  bills: number[];
  coins: number[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('app_language');
    if (saved && languages.some(l => l.code === saved)) {
      return saved as LanguageCode;
    }
    
    // Detect system language
    const systemLang = navigator.language;
    const matchedLang = languages.find(l => 
      systemLang.startsWith(l.code) || 
      (l.code === 'pt-BR' && (systemLang === 'pt-BR' || systemLang === 'pt'))
    );
    
    const defaultLang = matchedLang ? matchedLang.code : 'en';
    localStorage.setItem('app_language', defaultLang);
    return defaultLang;
  });

  // Sync with Firestore
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      if (user) {
        const userRef = doc(db, 'users', user.uid);
        const unsubDoc = onSnapshot(userRef, (docSnap) => {
          if (docSnap.exists()) {
            const data = docSnap.data();
            if (data.language && data.language !== language) {
              setLanguageState(data.language as LanguageCode);
              localStorage.setItem('app_language', data.language);
            }
          }
        }, (err) => {
          // Silent fail for permissions on initial load
          if (err.code !== 'permission-denied') {
            console.error("Firestore language sync error:", err);
          }
        });
        return () => unsubDoc();
      }
    });
    return () => unsubscribe();
  }, [language]);

  const setLanguage = async (code: LanguageCode) => {
    setLanguageState(code);
    localStorage.setItem('app_language', code);
    
    if (auth.currentUser) {
      try {
        const userRef = doc(db, 'users', auth.currentUser.uid);
        const docSnap = await getDoc(userRef);
        if (docSnap.exists()) {
          await updateDoc(userRef, { language: code });
        } else {
          // If doc doesn't exist, create it (App.tsx also does this, but redundancy is safe here)
          await setDoc(userRef, {
            uid: auth.currentUser.uid,
            email: auth.currentUser.email,
            displayName: auth.currentUser.displayName,
            photoURL: auth.currentUser.photoURL,
            role: auth.currentUser.email === 'mahteusmachado@gmail.com' ? 'admin' : 'seller',
            language: code,
          });
        }
      } catch (err) {
        // Log error but don't block UI
        console.error("Error saving language to Firestore:", err);
      }
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  const formatCurrency = (amount: number): string => {
    const lang = languages.find(l => l.code === language) || languages[0];
    return new Intl.NumberFormat(lang.locale, {
      style: 'currency',
      currency: lang.currency,
    }).format(amount);
  };

  const currentLanguage = languages.find(l => l.code === language) || languages[0];

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      t, 
      formatCurrency,
      bills: currentLanguage.bills,
      coins: currentLanguage.coins
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
