import React, { createContext, useContext, useState, ReactNode } from 'react';

export type LanguageCode = 'en' | 'pt-BR' | 'fr' | 'es' | 'de' | 'hi' | 'ru' | 'ja' | 'zh' | 'ko' | 'th';

interface Language {
  code: LanguageCode;
  name: string;
  flag: string;
  currency: string;
  locale: string;
}

export const languages: Language[] = [
  { code: 'en', name: 'English', flag: '🇺🇸', currency: 'USD', locale: 'en-US' },
  { code: 'pt-BR', name: 'Português (Brasil)', flag: '🇧🇷', currency: 'BRL', locale: 'pt-BR' },
  { code: 'fr', name: 'Français', flag: '🇫🇷', currency: 'EUR', locale: 'fr-FR' },
  { code: 'es', name: 'Español', flag: '🇪🇸', currency: 'EUR', locale: 'es-ES' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪', currency: 'EUR', locale: 'de-DE' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳', currency: 'INR', locale: 'hi-IN' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺', currency: 'RUB', locale: 'ru-RU' },
  { code: 'ja', name: '日本語', flag: '🇯🇵', currency: 'JPY', locale: 'ja-JP' },
  { code: 'zh', name: '中文', flag: '🇨🇳', currency: 'CNY', locale: 'zh-CN' },
  { code: 'ko', name: '한국어', flag: '🇰🇷', currency: 'KRW', locale: 'ko-KR' },
  { code: 'th', name: 'ไทย', flag: '🇹🇭', currency: 'THB', locale: 'th-TH' },
];

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    entries: 'Entries',
    history: 'History',
    profile: 'Profile',
    totalSales: 'Total Sales',
    monthlyGoal: 'Monthly Goal',
    recentSales: 'Recent Sales',
    newSale: 'New Sale',
    sellers: 'Sellers',
    management: 'Management',
    preferences: 'Preferences',
    darkMode: 'Dark Mode',
    language: 'Language',
    privacySettings: 'Privacy Settings',
    termsOfService: 'Terms of Service',
    deleteAccount: 'Delete Account',
    logout: 'Log out',
    adminProfile: 'Admin Profile',
    editProfile: 'Edit Profile',
    stores: 'Stores',
    manageRetail: 'Manage retail locations',
    staffPermissions: 'Staff & team permissions',
    onTrack: 'On Track',
    behind: 'Behind',
    completed: 'Completed',
    amount: 'Amount',
    paymentMethod: 'Payment Method',
    seller: 'Seller',
    save: 'Save',
    delete: 'Delete',
    cancel: 'Cancel',
    removeSeller: 'Remove Seller',
    editSeller: 'Edit Seller',
    newSeller: 'New Seller',
    sellerName: 'Seller Name',
    contactPhone: 'Contact/Phone',
    monthlySalesGoal: 'Monthly Sales Goal',
    observations: 'Observations',
    changePhoto: 'Change Photo',
    allSellers: 'All Sellers',
    activeSellers: 'Active Sellers',
    searchSellers: 'Search sellers...',
    noSalesYet: 'No sales recorded yet.',
    viewAll: 'View All',
    today: 'Today',
    yesterday: 'Yesterday',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    custom: 'Custom',
    selectDate: 'Select Date',
    selectWeek: 'Select Week',
    selectMonth: 'Select Month',
    salesTrend: 'Sales Trend',
    revenueByDay: 'Revenue by day',
    physicalStore: 'Physical Store',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'Sales Channels',
    performanceByPlatform: 'Performance by platform',
    total: 'Total',
    remaining: 'Remaining',
    currentSales: 'Current Sales',
    recentGoalProgress: 'Recent Goal Progress',
    ofTargetReached: 'of target reached',
    totalsByPaymentMethod: 'Totals by Payment Method',
    dailyView: 'Daily View',
    sellerPerformance: 'Seller Performance',
    grandTotal: 'Grand Total',
    salesToday: 'sales today',
    cash: 'Cash',
    credit: 'Credit',
    debit: 'Debit',
    pix: 'PIX',
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    goalResult: 'Goal Result',
    teamMembers: 'Team Members',
    addNew: 'Add New',
    noSellersYet: 'No sellers registered yet.',
    registerFirstSeller: 'Register First Seller',
    goal: 'Goal',
    confirmRemoveSeller: 'Are you sure you want to remove this seller?',
    fullName: 'Full Name',
    phonePlaceholder: '+1 (555) 000-0000',
    observationsPlaceholder: 'Add notes about performance, schedule, etc.',
    aiAssistant: 'AI Assistant',
    scanReceipt: 'Scan a receipt to auto-fill the form',
    analyzing: 'Analyzing...',
    scan: 'Scan',
    saleDetails: 'Sale Details',
    saving: 'Saving...',
    confirmSale: 'Confirm Sale',
    achievementUnlocked: 'Achievement Unlocked!',
    selectSeller: 'Select Seller',
    saleSource: 'Sale Source',
    cashBreakdown: 'Cash Breakdown',
    totalCash: 'Total Cash',
    confirmDeleteSale: 'Are you sure you want to delete this sale?',
    errorDeletingSale: 'Error deleting sale. Please try again.',
    noSalesFound: 'No sales found for this period.',
    bills: 'Bills',
    coins: 'Coins',
    performance: 'Performance',
    viewSale: 'View Sale',
    print: 'Print',
    confirmDelete: 'Are you sure you want to delete this?',
    welcomeMessage: 'Professional Sales Performance Dashboard',
    signInDescription: 'Sign in to access your dashboard and track your performance in real-time.',
    signInWithGoogle: 'Sign in with Google',
    authAgreement: 'By signing in, you agree to our Terms of Service and Privacy Policy.',
    applicationError: 'Application Error',
    somethingWentWrong: 'Something went wrong.',
    permissionDenied: "You don't have permission to perform this action. Please ensure you are an administrator.",
    reloadApplication: 'Reload Application',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    sun: 'Sun',
    w1: 'W1',
    w2: 'W2',
    w3: 'W3',
    w4: 'W4',
    bleed: 'Cash Out (Bleed)',
    reinforcement: 'Cash In (Reinforcement)',
    confirmMovement: 'Confirm Movement',
    addNotes: 'Add Notes/Coins',
    observation: 'Observation',
    confirm: 'Confirm',
    paymentMethodDetail: 'Payment Method Detail',
    netCash: 'Net Cash',
    totalSalesByMethod: 'Total Sales',
    totalSangrias: 'Total Sangrias',
    totalReforcos: 'Total Reinforcements',
    calculatedCash: 'Calculated Cash',
    summary: 'Summary',
  },
  'pt-BR': {
    dashboard: 'Painel',
    entries: 'Lançamentos',
    history: 'Histórico',
    profile: 'Perfil',
    totalSales: 'Vendas Totais',
    monthlyGoal: 'Meta Mensal',
    recentSales: 'Vendas Recentes',
    newSale: 'Nova Venda',
    sellers: 'Vendedores',
    management: 'Gerenciamento',
    preferences: 'Preferências',
    darkMode: 'Modo Escuro',
    language: 'Idioma',
    privacySettings: 'Configurações de Privacidade',
    termsOfService: 'Termos de Serviço',
    deleteAccount: 'Excluir Conta',
    logout: 'Sair',
    adminProfile: 'Perfil do Administrador',
    editProfile: 'Editar Perfil',
    stores: 'Lojas',
    manageRetail: 'Gerenciar locais de varejo',
    staffPermissions: 'Equipe e permissões',
    onTrack: 'No Prazo',
    behind: 'Atrasado',
    completed: 'Concluído',
    amount: 'Valor',
    paymentMethod: 'Método de Pagamento',
    seller: 'Vendedor',
    save: 'Salvar',
    delete: 'Excluir',
    cancel: 'Cancelar',
    removeSeller: 'Remover Vendedor',
    editSeller: 'Editar Vendedor',
    newSeller: 'Novo Vendedor',
    sellerName: 'Nome do Vendedor',
    contactPhone: 'Contato/Telefone',
    monthlySalesGoal: 'Meta de Vendas Mensal',
    observations: 'Observações',
    changePhoto: 'Alterar Foto',
    allSellers: 'Todos os Vendedores',
    activeSellers: 'Vendedores Ativos',
    searchSellers: 'Buscar vendedores...',
    noSalesYet: 'Nenhuma venda registrada ainda.',
    viewAll: 'Ver Tudo',
    today: 'Hoje',
    yesterday: 'Ontem',
    thisMonth: 'Este Mês',
    lastMonth: 'Mês Passado',
    day: 'Dia',
    week: 'Semana',
    month: 'Mês',
    custom: 'Personalizado',
    selectDate: 'Selecionar Data',
    selectWeek: 'Selecionar Semana',
    selectMonth: 'Selecionar Mês',
    salesTrend: 'Tendência de Vendas',
    revenueByDay: 'Receita por dia',
    physicalStore: 'Loja Física',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'Canais de Venda',
    performanceByPlatform: 'Desempenho por plataforma',
    total: 'Total',
    remaining: 'Restante',
    currentSales: 'Vendas Atuais',
    recentGoalProgress: 'Progresso Recente da Meta',
    ofTargetReached: 'da meta alcançada',
    totalsByPaymentMethod: 'Totais por Método de Pagamento',
    dailyView: 'Visualização Diária',
    sellerPerformance: 'Desempenho do Vendedor',
    grandTotal: 'Total Geral',
    salesToday: 'vendas hoje',
    cash: 'Dinheiro',
    credit: 'Crédito',
    debit: 'Débito',
    pix: 'PIX',
    last7Days: 'Últimos 7 Dias',
    last30Days: 'Últimos 30 Dias',
    goalResult: 'Resultado da Meta',
    teamMembers: 'Membros da Equipe',
    addNew: 'Adicionar Novo',
    noSellersYet: 'Nenhum vendedor registrado ainda.',
    registerFirstSeller: 'Registrar Primeiro Vendedor',
    goal: 'Meta',
    confirmRemoveSeller: 'Tem certeza que deseja remover este vendedor?',
    fullName: 'Nome Completo',
    phonePlaceholder: '(00) 00000-0000',
    observationsPlaceholder: 'Adicione notas sobre desempenho, horário, etc.',
    aiAssistant: 'Assistente de IA',
    scanReceipt: 'Escaneie um recibo para preencher o formulário',
    analyzing: 'Analisando...',
    scan: 'Escanear',
    saleDetails: 'Detalhes da Venda',
    saving: 'Salvando...',
    confirmSale: 'Confirmar Venda',
    achievementUnlocked: 'Conquista Desbloqueada!',
    selectSeller: 'Selecionar Vendedor',
    saleSource: 'Fonte da Venda',
    cashBreakdown: 'Detalhamento de Dinheiro',
    totalCash: 'Total em Dinheiro',
    confirmDeleteSale: 'Tem certeza que deseja excluir esta venda?',
    errorDeletingSale: 'Erro ao excluir venda. Tente novamente.',
    noSalesFound: 'Nenhuma venda encontrada para este período.',
    bills: 'Notas',
    coins: 'Moedas',
    performance: 'Desempenho',
    viewSale: 'Ver Venda',
    print: 'Imprimir',
    confirmDelete: 'Tem certeza que deseja excluir?',
    welcomeMessage: 'Painel Profissional de Desempenho de Vendas',
    signInDescription: 'Faça login para acessar seu painel e acompanhar seu desempenho em tempo real.',
    signInWithGoogle: 'Entrar com Google',
    authAgreement: 'Ao entrar, você concorda com nossos Termos de Serviço e Política de Privacidade.',
    applicationError: 'Erro na Aplicação',
    somethingWentWrong: 'Algo deu errado.',
    permissionDenied: 'Você não tem permissão para realizar esta ação. Certifique-se de que você é um administrador.',
    reloadApplication: 'Recarregar Aplicação',
    mon: 'Seg',
    tue: 'Ter',
    wed: 'Qua',
    thu: 'Qui',
    fri: 'Sex',
    sat: 'Sáb',
    sun: 'Dom',
    w1: 'S1',
    w2: 'S2',
    w3: 'S3',
    w4: 'S4',
    bleed: 'Sangria',
    reinforcement: 'Reforço',
    confirmMovement: 'Confirmar Movimentação',
    addNotes: 'Adicionar Notas/Moedas',
    observation: 'Observação',
    confirm: 'Confirmar',
    paymentMethodDetail: 'Detalhes do Método de Pagamento',
    netCash: 'Dinheiro Líquido',
    totalSalesByMethod: 'Vendas Totais',
    totalSangrias: 'Total de Sangrias',
    totalReforcos: 'Total de Reforços',
    calculatedCash: 'Dinheiro Calculado',
    summary: 'Resumo',
  },
  fr: {
    dashboard: 'Tableau de bord',
    entries: 'Entrées',
    history: 'Historique',
    profile: 'Profil',
    totalSales: 'Ventes totales',
    monthlyGoal: 'Objectif mensuel',
    recentSales: 'Ventes récentes',
    newSale: 'Nouvelle vente',
    sellers: 'Vendeurs',
    management: 'Gestion',
    preferences: 'Préférences',
    darkMode: 'Mode sombre',
    language: 'Langue',
    privacySettings: 'Paramètres de confidentialité',
    termsOfService: 'Conditions d\'utilisation',
    deleteAccount: 'Supprimer le compte',
    logout: 'Se déconnecter',
    adminProfile: 'Profil administrateur',
    editProfile: 'Modifier le profil',
    stores: 'Magasins',
    manageRetail: 'Gérer les points de vente',
    staffPermissions: 'Personnel et autorisations',
    onTrack: 'Sur la bonne voie',
    behind: 'En retard',
    completed: 'Terminé',
    amount: 'Montant',
    paymentMethod: 'Mode de paiement',
    seller: 'Vendeur',
    save: 'Enregistrer',
    cancel: 'Annuler',
    removeSeller: 'Supprimer le vendeur',
    editSeller: 'Modifier le vendeur',
    newSeller: 'Nouveau vendeur',
    sellerName: 'Nom du vendeur',
    contactPhone: 'Contact/Téléphone',
    monthlySalesGoal: 'Objectif de vente mensuel',
    observations: 'Observations',
    changePhoto: 'Changer la photo',
    allSellers: 'Tous les vendeurs',
    activeSellers: 'Vendeurs actifs',
    searchSellers: 'Rechercher des vendeurs...',
    noSalesYet: 'Aucune vente enregistrée.',
    viewAll: 'Voir tout',
    today: 'Aujourd\'hui',
    yesterday: 'Hier',
    thisMonth: 'Ce mois-ci',
    lastMonth: 'Le mois dernier',
    day: 'Jour',
    week: 'Semaine',
    month: 'Mois',
    custom: 'Personnalisé',
    selectDate: 'Choisir une date',
    selectWeek: 'Choisir une semaine',
    selectMonth: 'Choisir un mois',
    salesTrend: 'Tendance des ventes',
    revenueByDay: 'Revenu par jour',
    physicalStore: 'Magasin physique',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'Canaux de vente',
    performanceByPlatform: 'Performance par plateforme',
    total: 'Total',
    remaining: 'Restant',
    currentSales: 'Vendas atuais',
    recentGoalProgress: 'Progrès récent des objectifs',
    ofTargetReached: 'de l\'objectif atteint',
    totalsByPaymentMethod: 'Totaux par mode de paiement',
    dailyView: 'Vue quotidienne',
    sellerPerformance: 'Performance du vendeur',
    grandTotal: 'Total général',
    salesToday: 'ventes aujourd\'hui',
    cash: 'Espèces',
    credit: 'Crédit',
    debit: 'Débit',
    pix: 'PIX',
    last7Days: '7 derniers jours',
    last30Days: '30 derniers jours',
    goalResult: 'Résultat de l\'objectif',
    share: 'Partager',
    teamMembers: 'Membres de l\'équipe',
    addNew: 'Ajouter nouveau',
    noSellersYet: 'Aucun vendeur enregistré.',
    registerFirstSeller: 'Enregistrer le premier vendeur',
    goal: 'Objectif',
    confirmRemoveSeller: 'Voulez-vous vraiment supprimer ce vendeur ?',
    fullName: 'Nom complet',
    phonePlaceholder: '+33 0 00 00 00 00',
    observationsPlaceholder: 'Ajouter des notes sur la performance, etc.',
    aiAssistant: 'Assistant IA',
    scanReceipt: 'Scanner un reçu pour remplir le formulaire',
    analyzing: 'Analyse...',
    scan: 'Scanner',
    saleDetails: 'Détails de la vente',
    saving: 'Enregistrement...',
    confirmSale: 'Confirmer la vente',
    achievementUnlocked: 'Succès déverrouillé !',
    welcomeMessage: 'Tableau de bord professionnel des ventes',
    signInDescription: 'Connectez-vous pour accéder à votre tableau de bord.',
    signInWithGoogle: 'Se connecter avec Google',
    authAgreement: 'En vous connectant, vous acceptez nos conditions.',
    applicationError: 'Erreur d\'application',
    somethingWentWrong: 'Quelque chose s\'est mal passé.',
    permissionDenied: 'Vous n\'avez pas la permission.',
    reloadApplication: 'Recharger l\'application',
  },
  es: {
    dashboard: 'Tablero',
    entries: 'Entradas',
    history: 'Historial',
    profile: 'Perfil',
    totalSales: 'Ventas totales',
    monthlyGoal: 'Meta mensual',
    recentSales: 'Ventas recientes',
    newSale: 'Nueva venta',
    sellers: 'Vendedores',
    management: 'Gestión',
    preferences: 'Preferencias',
    darkMode: 'Modo oscuro',
    language: 'Idioma',
    privacySettings: 'Ajustes de privacidad',
    termsOfService: 'Términos de servicio',
    deleteAccount: 'Eliminar cuenta',
    logout: 'Cerrar sesión',
    adminProfile: 'Perfil de administrador',
    editProfile: 'Editar perfil',
    stores: 'Tiendas',
    manageRetail: 'Gestionar ubicaciones minoristas',
    staffPermissions: 'Personal y permisos',
    onTrack: 'En marcha',
    behind: 'Atrasado',
    completed: 'Completado',
    amount: 'Monto',
    paymentMethod: 'Método de pago',
    seller: 'Vendedor',
    save: 'Guardar',
    cancel: 'Cancelar',
    removeSeller: 'Eliminar vendedor',
    editSeller: 'Editar vendedor',
    newSeller: 'Nuevo vendedor',
    sellerName: 'Nombre del vendedor',
    contactPhone: 'Contacto/Teléfono',
    monthlySalesGoal: 'Meta de ventas mensual',
    observations: 'Observaciones',
    changePhoto: 'Cambiar foto',
    allSellers: 'Todos los vendedores',
    activeSellers: 'Vendedores activos',
    searchSellers: 'Buscar vendedores...',
    noSalesYet: 'No hay ventas registradas.',
    viewAll: 'Ver todo',
    today: 'Hoy',
    yesterday: 'Ayer',
    thisMonth: 'Este mes',
    lastMonth: 'Mes pasado',
    day: 'Día',
    week: 'Semana',
    month: 'Mes',
    custom: 'Personalizado',
    selectDate: 'Seleccionar fecha',
    selectWeek: 'Seleccionar semana',
    selectMonth: 'Seleccionar mes',
    salesTrend: 'Tendencia de ventas',
    revenueByDay: 'Ingresos por día',
    physicalStore: 'Tienda física',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'Canales de venta',
    performanceByPlatform: 'Rendimiento por plataforma',
    total: 'Total',
    remaining: 'Restante',
    currentSales: 'Ventas actuales',
    recentGoalProgress: 'Progreso reciente de metas',
    ofTargetReached: 'del objetivo alcanzado',
    totalsByPaymentMethod: 'Totales por método de pago',
    dailyView: 'Vista diaria',
    sellerPerformance: 'Rendimiento del vendedor',
    grandTotal: 'Gran total',
    salesToday: 'ventas hoy',
    cash: 'Efectivo',
    credit: 'Crédito',
    debit: 'Débito',
    pix: 'PIX',
    last7Days: 'Últimos 7 días',
    last30Days: 'Últimos 30 días',
    goalResult: 'Resultado de meta',
    share: 'Compartir',
    teamMembers: 'Miembros del equipo',
    addNew: 'Agregar nuevo',
    noSellersYet: 'No hay vendedores registrados.',
    registerFirstSeller: 'Registrar primer vendedor',
    goal: 'Meta',
    confirmRemoveSeller: '¿Estás seguro de eliminar este vendedor?',
    fullName: 'Nombre completo',
    phonePlaceholder: '+34 000 000 000',
    observationsPlaceholder: 'Agregar notas sobre el rendimiento, etc.',
    aiAssistant: 'Asistente de IA',
    scanReceipt: 'Escanear un recibo para completar el formulario',
    analyzing: 'Analizando...',
    scan: 'Escanear',
    saleDetails: 'Detalles de la venta',
    saving: 'Guardando...',
    confirmSale: 'Confirmar venta',
    achievementUnlocked: '¡Logro desbloqueado!',
    welcomeMessage: 'Tablero profesional de ventas',
    signInDescription: 'Inicia sesión para acceder a tu tablero.',
    signInWithGoogle: 'Iniciar sesión con Google',
    authAgreement: 'Al iniciar sesión, aceptas nuestros términos.',
    applicationError: 'Error de aplicación',
    somethingWentWrong: 'Algo salió mal.',
    permissionDenied: 'No tienes permiso.',
    reloadApplication: 'Recargar aplicación',
    bleed: 'Sangría',
    reinforcement: 'Refuerzo',
    confirmMovement: 'Confirmar Movimiento',
    addNotes: 'Agregar Billetes/Monedas',
    observation: 'Observación',
    confirm: 'Confirmar',
    paymentMethodDetail: 'Detalles del Método de Pago',
    netCash: 'Efectivo Neto',
    totalSalesByMethod: 'Ventas Totales',
    totalSangrias: 'Total de Sangrías',
    totalReforcos: 'Total de Refuerzos',
    calculatedCash: 'Efectivo Calculado',
    summary: 'Resumen',
  },
  de: {
    dashboard: 'Dashboard',
    entries: 'Einträge',
    history: 'Verlauf',
    profile: 'Profil',
    totalSales: 'Gesamtumsatz',
    monthlyGoal: 'Monatsziel',
    recentSales: 'Aktuelle Verkäufe',
    newSale: 'Neuer Verkauf',
    sellers: 'Verkäufer',
    management: 'Verwaltung',
    preferences: 'Einstellungen',
    darkMode: 'Dunkelmodus',
    language: 'Sprache',
    privacySettings: 'Datenschutz',
    termsOfService: 'Nutzungsbedingungen',
    deleteAccount: 'Konto löschen',
    logout: 'Abmelden',
    adminProfile: 'Admin-Profil',
    editProfile: 'Profil bearbeiten',
    stores: 'Filialen',
    manageRetail: 'Einzelhandelsstandorte verwalten',
    staffPermissions: 'Personal & Berechtigungen',
    onTrack: 'Im Plan',
    behind: 'Im Verzug',
    completed: 'Abgeschlossen',
    amount: 'Betrag',
    paymentMethod: 'Zahlungsart',
    seller: 'Verkäufer',
    save: 'Speichern',
    cancel: 'Abbrechen',
    removeSeller: 'Verkäufer entfernen',
    editSeller: 'Verkäufer bearbeiten',
    newSeller: 'Neuer Verkäufer',
    sellerName: 'Name des Verkäufers',
    contactPhone: 'Kontakt/Telefon',
    monthlySalesGoal: 'Monatliches Verkaufsziel',
    observations: 'Beobachtungen',
    changePhoto: 'Foto ändern',
    allSellers: 'Alle Verkäufer',
    activeSellers: 'Aktive Verkäufer',
    searchSellers: 'Verkäufer suchen...',
    noSalesYet: 'Noch keine Verkäufe.',
    viewAll: 'Alle anzeigen',
    today: 'Heute',
    yesterday: 'Gestern',
    thisMonth: 'Diesen Monat',
    lastMonth: 'Letzten Monat',
    day: 'Tag',
    week: 'Woche',
    month: 'Monat',
    custom: 'Benutzerdefiniert',
    selectDate: 'Datum auswählen',
    selectWeek: 'Woche auswählen',
    selectMonth: 'Monat auswählen',
    salesTrend: 'Verkaufstrend',
    revenueByDay: 'Umsatz nach Tag',
    physicalStore: 'Ladengeschäft',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'Verkaufskanäle',
    performanceByPlatform: 'Leistung nach Plattform',
    total: 'Gesamt',
    remaining: 'Verbleibend',
    currentSales: 'Aktuelle Verkäufe',
    recentGoalProgress: 'Aktueller Zielfortschritt',
    ofTargetReached: 'des Ziels erreicht',
    totalsByPaymentMethod: 'Gesamtbeträge nach Zahlungsart',
    dailyView: 'Tagesansicht',
    sellerPerformance: 'Verkäuferleistung',
    grandTotal: 'Gesamtsumme',
    salesToday: 'Verkäufe heute',
    cash: 'Bar',
    credit: 'Kredit',
    debit: 'Lastschrift',
    pix: 'PIX',
    last7Days: 'Letzte 7 Tage',
    last30Days: 'Letzte 30 Tage',
    goalResult: 'Zielergebnis',
    share: 'Teilen',
    teamMembers: 'Teammitglieder',
    addNew: 'Neu hinzufügen',
    noSellersYet: 'Noch keine Verkäufer registriert.',
    registerFirstSeller: 'Ersten Verkäufer registrieren',
    goal: 'Ziel',
    confirmRemoveSeller: 'Sind Sie sicher, dass Sie diesen Verkäufer entfernen möchten?',
    fullName: 'Vollständiger Name',
    phonePlaceholder: '+49 000 00000000',
    observationsPlaceholder: 'Notizen zur Leistung, Zeitplan usw. hinzufügen',
    aiAssistant: 'KI-Assistent',
    scanReceipt: 'Beleg scannen, um das Formular automatisch auszufüllen',
    analyzing: 'Analysiere...',
    scan: 'Scannen',
    saleDetails: 'Verkaufsdetails',
    saving: 'Speichere...',
    confirmSale: 'Verkauf bestätigen',
    achievementUnlocked: 'Erfolg freigeschaltet!',
    welcomeMessage: 'Professionelles Verkaufs-Dashboard',
    signInDescription: 'Melden Sie sich an, um auf Ihr Dashboard zuzugreifen.',
    signInWithGoogle: 'Mit Google anmelden',
    authAgreement: 'Mit der Anmeldung stimmen Sie unseren Bedingungen zu.',
    applicationError: 'Anwendungsfehler',
    somethingWentWrong: 'Etwas ist schief gelaufen.',
    permissionDenied: 'Keine Berechtigung.',
    reloadApplication: 'Anwendung neu laden',
    mon: 'Mo',
    tue: 'Di',
    wed: 'Mi',
    thu: 'Do',
    fri: 'Fr',
    sat: 'Sa',
    sun: 'So',
    w1: 'W1',
    w2: 'W2',
    w3: 'W3',
    w4: 'W4',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    entries: 'प्रविष्टियाँ',
    history: 'इतिहास',
    profile: 'प्रोफ़ाइल',
    totalSales: 'कुल बिक्री',
    monthlyGoal: 'मासिक लक्ष्य',
    recentSales: 'हाल की बिक्री',
    newSale: 'नई बिक्री',
    sellers: 'विक्रेता',
    management: 'प्रबंधन',
    preferences: 'प्राथमिकताएं',
    darkMode: 'डार्क मोड',
    language: 'भाषा',
    privacySettings: 'गोपनीयता सेटिंग्स',
    termsOfService: 'सेवा की शर्तें',
    deleteAccount: 'खाता हटाएं',
    logout: 'लॉग आउट',
    adminProfile: 'एडमिन प्रोफ़ाइल',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    stores: 'स्टोर',
    manageRetail: 'रिटेल स्थानों का प्रबंधन करें',
    staffPermissions: 'स्टाफ और टीम अनुमतियां',
    onTrack: 'ट्रैक पर',
    behind: 'पीछे',
    completed: 'पूरा हुआ',
    amount: 'राशि',
    paymentMethod: 'भुगतान विधि',
    seller: 'विक्रेता',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    removeSeller: 'विक्रेता को हटाएं',
    editSeller: 'विक्रेता को संपादित करें',
    newSeller: 'नया विक्रेता',
    sellerName: 'विक्रेता का नाम',
    contactPhone: 'संपर्क/फ़ोन',
    monthlySalesGoal: 'मासिक बिक्री लक्ष्य',
    observations: 'अवलोकन',
    changePhoto: 'फोटो बदलें',
    allSellers: 'सभी विक्रेता',
    activeSellers: 'सक्रिय विक्रेता',
    searchSellers: 'विक्रेता खोजें...',
    noSalesYet: 'अभी तक कोई बिक्री दर्ज नहीं की गई।',
    viewAll: 'सभी देखें',
    today: 'आज',
    yesterday: 'कल',
    thisMonth: 'इस महीने',
    lastMonth: 'पिछले महीने',
    day: 'दिन',
    week: 'सप्ताह',
    month: 'महीना',
    custom: 'कस्टम',
    selectDate: 'तारीख चुनें',
    selectWeek: 'सप्ताह चुनें',
    selectMonth: 'महीना चुनें',
    salesTrend: 'बिक्री का रुझान',
    revenueByDay: 'दिन के अनुसार राजस्व',
    physicalStore: 'भौतिक स्टोर',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'बिक्री चैनल',
    performanceByPlatform: 'प्लेटफ़ॉर्म के अनुसार प्रदर्शन',
    total: 'कुल',
    remaining: 'शेष',
    currentSales: 'वर्तमान बिक्री',
    recentGoalProgress: 'हालिया लक्ष्य प्रगति',
    ofTargetReached: 'लक्ष्य तक पहुँच गया',
    totalsByPaymentMethod: 'भुगतान विधि द्वारा कुल',
    dailyView: 'दैनिक दृश्य',
    sellerPerformance: 'विक्रेता प्रदर्शन',
    grandTotal: 'कुल योग',
    salesToday: 'आज की बिक्री',
    cash: 'नकद',
    credit: 'क्रेडिट',
    debit: 'डेबिट',
    pix: 'PIX',
    last7Days: 'पिछले 7 दिन',
    last30Days: 'पिछले 30 दिन',
    goalResult: 'लक्ष्य परिणाम',
    share: 'साझा करें',
    teamMembers: 'टीम के सदस्य',
    addNew: 'नया जोड़ें',
    noSellersYet: 'अभी तक कोई विक्रेता पंजीकृत नहीं है।',
    registerFirstSeller: 'पहला विक्रेता पंजीकृत करें',
    goal: 'लक्ष्य',
    confirmRemoveSeller: 'क्या आप वाकई इस विक्रेता को हटाना चाहते हैं?',
    fullName: 'पूरा नाम',
    phonePlaceholder: '+91 00000 00000',
    observationsPlaceholder: 'प्रदर्शन, शेड्यूल आदि के बारे में नोट्स जोड़ें।',
    aiAssistant: 'AI सहायक',
    scanReceipt: 'फॉर्म भरने के लिए रसीद स्कैन करें',
    analyzing: 'विश्लेषण कर रहा है...',
    scan: 'स्कैन',
    saleDetails: 'बिक्री विवरण',
    saving: 'सहेज रहा है...',
    confirmSale: 'बिक्री की पुष्टि करें',
    achievementUnlocked: 'उपलब्धि अनलॉक!',
    welcomeMessage: 'पेशेवर बिक्री प्रदर्शन डैशबोर्ड',
    signInDescription: 'अपने डैशबोर्ड तक पहुँचने के लिए साइन इन करें।',
    signInWithGoogle: 'Google के साथ साइन इन करें',
    authAgreement: 'साइन इन करके, आप हमारी शर्तों से सहमत होते हैं।',
    applicationError: 'एप्लिकेशन त्रुटि',
    somethingWentWrong: 'कुछ गलत हो गया।',
    permissionDenied: 'अनुमति नहीं है।',
    reloadApplication: 'एप्लिकेशन को फिर से लोड करें',
    mon: 'सोम',
    tue: 'मंगल',
    wed: 'बुध',
    thu: 'गुरु',
    fri: 'शुक्र',
    sat: 'शनि',
    sun: 'रवि',
    w1: 'स1',
    w2: 'स2',
    w3: 'स3',
    w4: 'स4',
  },
  ru: {
    dashboard: 'Панель',
    entries: 'Записи',
    history: 'История',
    profile: 'Профиль',
    totalSales: 'Всего продаж',
    monthlyGoal: 'Месячная цель',
    recentSales: 'Последние продажи',
    newSale: 'Новая продажа',
    sellers: 'Продавцы',
    management: 'Управление',
    preferences: 'Настройки',
    darkMode: 'Темный режим',
    language: 'Язык',
    privacySettings: 'Конфиденциальность',
    termsOfService: 'Условия использования',
    deleteAccount: 'Удалить аккаунт',
    logout: 'Выйти',
    adminProfile: 'Профиль админа',
    editProfile: 'Редактировать профиль',
    stores: 'Магазины',
    manageRetail: 'Управление точками',
    staffPermissions: 'Персонал и права',
    onTrack: 'В графике',
    behind: 'Отстает',
    completed: 'Завершено',
    amount: 'Сумма',
    paymentMethod: 'Способ оплаты',
    seller: 'Продавец',
    save: 'Сохранить',
    cancel: 'Отмена',
    removeSeller: 'Удалить продавца',
    editSeller: 'Редактировать продавца',
    newSeller: 'Новый продавец',
    sellerName: 'Имя продавца',
    contactPhone: 'Контакт/Телефон',
    monthlySalesGoal: 'Месячный план продаж',
    observations: 'Примечания',
    changePhoto: 'Изменить фото',
    allSellers: 'Все продавцы',
    activeSellers: 'Активные продавцы',
    searchSellers: 'Поиск продавцов...',
    noSalesYet: 'Продаж пока нет.',
    viewAll: 'Показать все',
    today: 'Сегодня',
    yesterday: 'Вчера',
    thisMonth: 'В этом месяце',
    lastMonth: 'В прошлом месяце',
    day: 'День',
    week: 'Неделя',
    month: 'Месяц',
    custom: 'Пользовательский',
    selectDate: 'Выбрать дату',
    selectWeek: 'Выбрать неделю',
    selectMonth: 'Выбрать месяц',
    salesTrend: 'Тенденция продаж',
    revenueByDay: 'Выручка по дням',
    physicalStore: 'Магазин',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'Каналы продаж',
    performanceByPlatform: 'Эффективность платформ',
    total: 'Всего',
    remaining: 'Осталось',
    currentSales: 'Текущие продажи',
    recentGoalProgress: 'Прогресс целей',
    ofTargetReached: 'цели достигнуто',
    totalsByPaymentMethod: 'Итоги по способам оплаты',
    dailyView: 'Дневной вид',
    sellerPerformance: 'Эффективность продавцов',
    grandTotal: 'Общий итог',
    salesToday: 'продаж сегодня',
    cash: 'Наличные',
    credit: 'Кредит',
    debit: 'Дебет',
    pix: 'PIX',
    last7Days: 'Последние 7 дней',
    last30Days: 'Последние 30 дней',
    goalResult: 'Результат цели',
    share: 'Поделиться',
    teamMembers: 'Члены команды',
    addNew: 'Добавить',
    noSellersYet: 'Продавцы не зарегистрированы.',
    registerFirstSeller: 'Зарегистрировать первого продавца',
    goal: 'Цель',
    confirmRemoveSeller: 'Вы уверены, что хотите удалить продавца?',
    fullName: 'Полное имя',
    phonePlaceholder: '+7 000 000-00-00',
    observationsPlaceholder: 'Примечания к работе и т.д.',
    aiAssistant: 'ИИ-помощник',
    scanReceipt: 'Сканируйте чек для автозаполнения',
    analyzing: 'Анализ...',
    scan: 'Сканировать',
    saleDetails: 'Детали продажи',
    saving: 'Сохранение...',
    confirmSale: 'Подтвердить продажу',
    achievementUnlocked: 'Достижение разблокировано!',
    welcomeMessage: 'Профессиональная панель продаж',
    signInDescription: 'Войдите, чтобы получить доступ к панели.',
    signInWithGoogle: 'Войти через Google',
    authAgreement: 'Входя, вы соглашаетесь с условиями.',
    applicationError: 'Ошибка приложения',
    somethingWentWrong: 'Что-то пошло не так.',
    permissionDenied: 'Доступ запрещен.',
    reloadApplication: 'Перезагрузить приложение',
    mon: 'Пн',
    tue: 'Вт',
    wed: 'Ср',
    thu: 'Чт',
    fri: 'Пт',
    sat: 'Сб',
    sun: 'Вс',
    w1: 'Н1',
    w2: 'Н2',
    w3: 'Н3',
    w4: 'Н4',
  },
  ja: {
    dashboard: 'ダッシュボード',
    entries: '入力',
    history: '履歴',
    profile: 'プロフィール',
    totalSales: '総売上',
    monthlyGoal: '月間目標',
    recentSales: '最近の売上',
    newSale: '新規売上',
    sellers: '販売員',
    management: '管理',
    preferences: '設定',
    darkMode: 'ダークモード',
    language: '言語',
    privacySettings: 'プライバシー設定',
    termsOfService: '利用規約',
    deleteAccount: 'アカウント削除',
    logout: 'ログアウト',
    adminProfile: '管理者プロフィール',
    editProfile: 'プロフィール編集',
    stores: '店舗',
    manageRetail: '小売拠点の管理',
    staffPermissions: 'スタッフと権限',
    onTrack: '順調',
    behind: '遅延',
    completed: '完了',
    amount: '金額',
    paymentMethod: '支払い方法',
    seller: '販売員',
    save: '保存',
    cancel: 'キャンセル',
    removeSeller: '販売員を削除',
    editSeller: '販売員を編集',
    newSeller: '新規販売員',
    sellerName: '販売員名',
    contactPhone: '連絡先/電話',
    monthlySalesGoal: '月間売上目標',
    observations: '備考',
    changePhoto: '写真を変更',
    allSellers: '全販売員',
    activeSellers: 'アクティブな販売員',
    searchSellers: '販売員を検索...',
    noSalesYet: '売上はまだありません。',
    viewAll: 'すべて表示',
    today: '今日',
    yesterday: '昨日',
    thisMonth: '今月',
    lastMonth: '先月',
    day: '日',
    week: '週',
    month: '月',
    custom: 'カスタム',
    selectDate: '日付を選択',
    selectWeek: '週を選択',
    selectMonth: '月を選択',
    salesTrend: '売上トレンド',
    revenueByDay: '日別収益',
    physicalStore: '実店舗',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: '販売チャネル',
    performanceByPlatform: 'プラットフォーム別パフォーマンス',
    total: '合計',
    remaining: '残り',
    currentSales: '現在の売上',
    recentGoalProgress: '最近の目標進捗',
    ofTargetReached: 'の目標達成',
    totalsByPaymentMethod: '支払い方法別合計',
    dailyView: '日別表示',
    sellerPerformance: '販売員パフォーマンス',
    grandTotal: '総合計',
    salesToday: '今日の売上',
    cash: '現金',
    credit: 'クレジット',
    debit: 'デビット',
    pix: 'PIX',
    last7Days: '過去7日間',
    last30Days: '過去30日間',
    goalResult: '目標結果',
    share: '共有',
    teamMembers: 'チームメンバー',
    addNew: '新規追加',
    noSellersYet: '販売員が登録されていません。',
    registerFirstSeller: '最初の販売員を登録',
    goal: '目標',
    confirmRemoveSeller: 'この販売員を削除してもよろしいですか？',
    fullName: 'フルネーム',
    phonePlaceholder: '000-0000-0000',
    observationsPlaceholder: 'パフォーマンスやスケジュールなどのメモを追加',
    aiAssistant: 'AIアシスタント',
    scanReceipt: 'レシートをスキャンして自動入力',
    analyzing: '分析中...',
    scan: 'スキャン',
    saleDetails: '売上詳細',
    saving: '保存中...',
    confirmSale: '売上を確定',
    achievementUnlocked: '実績解除！',
    welcomeMessage: 'プロフェッショナル売上ダッシュボード',
    signInDescription: 'ダッシュボードにアクセスするにはサインインしてください。',
    signInWithGoogle: 'Googleでサインイン',
    authAgreement: 'サインインすることで、利用規約とプライバシーポリシーに同意したことになります。',
    applicationError: 'アプリケーションエラー',
    somethingWentWrong: '問題が発生しました。',
    permissionDenied: '権限がありません。',
    reloadApplication: 'アプリを再読み込み',
    mon: '月',
    tue: '火',
    wed: '水',
    thu: '木',
    fri: '金',
    sat: '土',
    sun: '日',
    w1: '第1週',
    w2: '第2週',
    w3: '第3週',
    w4: '第4週',
  },
  zh: {
    dashboard: '仪表板',
    entries: '条目',
    history: '历史',
    profile: '个人资料',
    totalSales: '总销售额',
    monthlyGoal: '每月目标',
    recentSales: '最近销售',
    newSale: '新增销售',
    sellers: '销售员',
    management: '管理',
    preferences: '首选项',
    darkMode: '深色模式',
    language: '语言',
    privacySettings: '隐私设置',
    termsOfService: '服务条款',
    deleteAccount: '删除账户',
    logout: '退出登录',
    adminProfile: '管理员资料',
    editProfile: '编辑资料',
    stores: '商店',
    manageRetail: '管理零售地点',
    staffPermissions: '员工和团队权限',
    onTrack: '正常',
    behind: '落后',
    completed: '已完成',
    amount: '金额',
    paymentMethod: '付款方式',
    seller: '销售员',
    save: '保存',
    cancel: '取消',
    removeSeller: '移除销售员',
    editSeller: '编辑销售员',
    newSeller: '新增销售员',
    sellerName: '销售员姓名',
    contactPhone: '联系方式/电话',
    monthlySalesGoal: '每月销售目标',
    observations: '备注',
    changePhoto: '更换照片',
    allSellers: '所有销售员',
    activeSellers: '活跃销售员',
    searchSellers: '搜索销售员...',
    noSalesYet: '暂无销售记录。',
    viewAll: '查看全部',
    today: '今天',
    yesterday: '昨天',
    thisMonth: '本月',
    lastMonth: '上月',
    day: '日',
    week: '周',
    month: '月',
    custom: '自定义',
    selectDate: '选择日期',
    selectWeek: '选择周',
    selectMonth: '选择月',
    salesTrend: '销售趋势',
    revenueByDay: '每日收入',
    physicalStore: '实体店',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: '销售渠道',
    performanceByPlatform: '平台绩效',
    total: '总计',
    remaining: '剩余',
    currentSales: '当前销售',
    recentGoalProgress: '近期目标进度',
    ofTargetReached: '目标已达成',
    totalsByPaymentMethod: '按付款方式统计',
    dailyView: '每日视图',
    sellerPerformance: '销售员绩效',
    grandTotal: '总计',
    salesToday: '今日销售',
    cash: '现金',
    credit: '信用卡',
    debit: '借记卡',
    pix: 'PIX',
    last7Days: '最近7天',
    last30Days: '最近30天',
    goalResult: '目标结果',
    share: '分享',
    teamMembers: '团队成员',
    addNew: '新增',
    noSellersYet: '暂无销售员。',
    registerFirstSeller: '注册首位销售员',
    goal: '目标',
    confirmRemoveSeller: '确定要移除该销售员吗？',
    fullName: '全名',
    phonePlaceholder: '000-0000-0000',
    observationsPlaceholder: '添加关于绩效、排班等的备注',
    aiAssistant: 'AI 助手',
    scanReceipt: '扫描收据自动填写',
    analyzing: '分析中...',
    scan: '扫描',
    saleDetails: '销售详情',
    saving: '保存中...',
    confirmSale: '确认销售',
    achievementUnlocked: '成就已解锁！',
    welcomeMessage: '专业销售绩效仪表板',
    signInDescription: '登录以访问您的仪表板。',
    signInWithGoogle: '使用 Google 登录',
    authAgreement: '登录即表示您同意我们的条款。',
    applicationError: '应用错误',
    somethingWentWrong: '出错了。',
    permissionDenied: '无权限。',
    reloadApplication: '重新加载应用',
    mon: '周一',
    tue: '周二',
    wed: '周三',
    thu: '周四',
    fri: '周五',
    sat: '周六',
    sun: '周日',
    w1: '第一周',
    w2: '第二周',
    w3: '第三周',
    w4: '第四周',
  },
  ko: {
    dashboard: '대시보드',
    entries: '입력',
    history: '내역',
    profile: '프로필',
    totalSales: '총 매출',
    monthlyGoal: '월간 목표',
    recentSales: '최근 매출',
    newSale: '신규 매출',
    sellers: '판매원',
    management: '관리',
    preferences: '설정',
    darkMode: '다크 모드',
    language: '언어',
    privacySettings: '개인정보 설정',
    termsOfService: '서비스 약관',
    deleteAccount: '계정 삭제',
    logout: '로그아웃',
    adminProfile: '관리자 프로필',
    editProfile: '프로필 수정',
    stores: '매장',
    manageRetail: '소매 위치 관리',
    staffPermissions: '직원 및 팀 권한',
    onTrack: '정상',
    behind: '지연',
    completed: '완료',
    amount: '금액',
    paymentMethod: '결제 방법',
    seller: '판매원',
    save: '저장',
    cancel: '취소',
    removeSeller: '판매원 삭제',
    editSeller: '판매원 수정',
    newSeller: '신규 판매원',
    sellerName: '판매원 이름',
    contactPhone: '연락처/전화번호',
    monthlySalesGoal: '월간 매출 목표',
    observations: '비고',
    changePhoto: '사진 변경',
    allSellers: '모든 판매원',
    activeSellers: '활성 판매원',
    searchSellers: '판매원 검색...',
    noSalesYet: '매출 기록이 없습니다.',
    viewAll: '모두 보기',
    today: '오늘',
    yesterday: '어제',
    thisMonth: '이번 달',
    lastMonth: '지난 달',
    day: '일',
    week: '주',
    month: '월',
    custom: '사용자 정의',
    selectDate: '날짜 선택',
    selectWeek: '주 선택',
    selectMonth: '월 선택',
    salesTrend: '매출 트렌드',
    revenueByDay: '일별 수익',
    physicalStore: '오프라인 매장',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: '판매 채널',
    performanceByPlatform: '플랫폼별 성과',
    total: '합계',
    remaining: '남음',
    currentSales: '현재 매출',
    recentGoalProgress: '최근 목표 진행 상황',
    ofTargetReached: '목표 달성',
    totalsByPaymentMethod: '결제 방법별 합계',
    dailyView: '일별 보기',
    sellerPerformance: '판매원 성과',
    grandTotal: '총합계',
    salesToday: '오늘의 판매',
    cash: '현금',
    credit: '신용카드',
    debit: '직불카드',
    pix: 'PIX',
    last7Days: '최근 7일',
    last30Days: '최근 30일',
    goalResult: '목표 결과',
    share: '공유',
    teamMembers: '팀원',
    addNew: '새로 추가',
    noSellersYet: '등록된 판매원이 없습니다.',
    registerFirstSeller: '첫 판매원 등록',
    goal: '목표',
    confirmRemoveSeller: '이 판매원을 삭제하시겠습니까?',
    fullName: '성함',
    phonePlaceholder: '010-0000-0000',
    observationsPlaceholder: '성과, 일정 등에 대한 메모 추가',
    aiAssistant: 'AI 어시스턴트',
    scanReceipt: '영수증을 스캔하여 양식 자동 채우기',
    analyzing: '분석 중...',
    scan: '스캔',
    saleDetails: '판매 상세 정보',
    saving: '저장 중...',
    confirmSale: '판매 확인',
    achievementUnlocked: '업적 달성!',
    welcomeMessage: '전문 판매 성과 대시보드',
    signInDescription: '대시보드에 액세스하려면 로그인하세요.',
    signInWithGoogle: 'Google로 로그인',
    authAgreement: '로그인하면 약관에 동의하는 것으로 간주됩니다.',
    applicationError: '애플리케이션 오류',
    somethingWentWrong: '문제가 발생했습니다.',
    permissionDenied: '권한이 없습니다.',
    reloadApplication: '앱 다시 로드',
    mon: '월',
    tue: '화',
    wed: '수',
    thu: '목',
    fri: '금',
    sat: '토',
    sun: '일',
    w1: '1주',
    w2: '2주',
    w3: '3주',
    w4: '4주',
  },
  th: {
    dashboard: 'แดชบอร์ด',
    entries: 'รายการ',
    history: 'ประวัติ',
    profile: 'โปรไฟล์',
    totalSales: 'ยอดขายรวม',
    monthlyGoal: 'เป้าหมายรายเดือน',
    recentSales: 'ยอดขายล่าสุด',
    newSale: 'เพิ่มยอดขาย',
    sellers: 'พนักงานขาย',
    management: 'การจัดการ',
    preferences: 'การตั้งค่า',
    darkMode: 'โหมดมืด',
    language: 'ภาษา',
    privacySettings: 'การตั้งค่าความเป็นส่วนตัว',
    termsOfService: 'ข้อกำหนดการให้บริการ',
    deleteAccount: 'ลบบัญชี',
    logout: 'ออกจากระบบ',
    adminProfile: 'โปรไฟล์ผู้ดูแลระบบ',
    editProfile: 'แก้ไขโปรไฟล์',
    stores: 'ร้านค้า',
    manageRetail: 'จัดการสถานที่ค้าปลีก',
    staffPermissions: 'พนักงานและสิทธิ์ทีม',
    onTrack: 'ตามแผน',
    behind: 'ล่าช้า',
    completed: 'เสร็จสมบูรณ์',
    amount: 'จำนวนเงิน',
    paymentMethod: 'วิธีการชำระเงิน',
    seller: 'พนักงานขาย',
    save: 'บันทึก',
    cancel: 'ยกเลิก',
    removeSeller: 'ลบพนักงานขาย',
    editSeller: 'แก้ไขพนักงานขาย',
    newSeller: 'พนักงานขายใหม่',
    sellerName: 'ชื่อพนักงานขาย',
    contactPhone: 'ติดต่อ/โทรศัพท์',
    monthlySalesGoal: 'เป้าหมายการขายรายเดือน',
    observations: 'หมายเหตุ',
    changePhoto: 'เปลี่ยนรูปภาพ',
    allSellers: 'พนักงานขายทั้งหมด',
    activeSellers: 'พนักงานขายที่ใช้งานอยู่',
    searchSellers: 'ค้นหาพนักงานขาย...',
    noSalesYet: 'ยังไม่มีบันทึกยอดขาย',
    viewAll: 'ดูทั้งหมด',
    today: 'วันนี้',
    yesterday: 'เมื่อวาน',
    thisMonth: 'เดือนนี้',
    lastMonth: 'เดือนที่แล้ว',
    day: 'วัน',
    week: 'สัปดาห์',
    month: 'เดือน',
    custom: 'กำหนดเอง',
    selectDate: 'เลือกวันที่',
    selectWeek: 'เลือกสัปดาห์',
    selectMonth: 'เลือกเดือน',
    salesTrend: 'แนวโน้มยอดขาย',
    revenueByDay: 'รายได้ตามวัน',
    physicalStore: 'หน้าร้าน',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    salesChannels: 'ช่องทางการขาย',
    performanceByPlatform: 'ประสิทธิภาพตามแพลตฟอร์ม',
    total: 'รวม',
    remaining: 'คงเหลือ',
    currentSales: 'ยอดขายปัจจุบัน',
    recentGoalProgress: 'ความคืบหน้าเป้าหมายล่าสุด',
    ofTargetReached: 'ของเป้าหมายที่บรรลุ',
    totalsByPaymentMethod: 'ยอดรวมตามวิธีการชำระเงิน',
    dailyView: 'มุมมองรายวัน',
    sellerPerformance: 'ประสิทธิภาพพนักงานขาย',
    grandTotal: 'ยอดรวมทั้งหมด',
    salesToday: 'ยอดขายวันนี้',
    cash: 'เงินสด',
    credit: 'บัตรเครดิต',
    debit: 'บัตรเดบิต',
    pix: 'PIX',
    last7Days: '7 วันที่ผ่านมา',
    last30Days: '30 วันที่ผ่านมา',
    goalResult: 'ผลลัพธ์เป้าหมาย',
    share: 'แชร์',
    teamMembers: 'สมาชิกในทีม',
    addNew: 'เพิ่มใหม่',
    noSellersYet: 'ยังไม่มีพนักงานขายที่ลงทะเบียน',
    registerFirstSeller: 'ลงทะเบียนพนักงานขายคนแรก',
    goal: 'เป้าหมาย',
    confirmRemoveSeller: 'คุณแน่ใจหรือไม่ว่าต้องการลบพนักงานขายคนนี้?',
    fullName: 'ชื่อ-นามสกุล',
    phonePlaceholder: '081-000-0000',
    observationsPlaceholder: 'เพิ่มบันทึกเกี่ยวกับประสิทธิภาพ ตารางเวลา ฯลฯ',
    aiAssistant: 'ผู้ช่วย AI',
    scanReceipt: 'สแกนใบเสร็จเพื่อกรอกแบบฟอร์มอัตโนมัติ',
    analyzing: 'กำลังวิเคราะห์...',
    scan: 'สแกน',
    saleDetails: 'รายละเอียดการขาย',
    saving: 'กำลังบันทึก...',
    confirmSale: 'ยืนยันการขาย',
    achievementUnlocked: 'ปลดล็อกความสำเร็จ!',
    welcomeMessage: 'แดชบอร์ดประสิทธิภาพการขายระดับมืออาชีพ',
    signInDescription: 'ลงชื่อเข้าใช้เพื่อเข้าถึงแดชบอร์ดของคุณ',
    signInWithGoogle: 'ลงชื่อเข้าใช้ด้วย Google',
    authAgreement: 'การลงชื่อเข้าใช้แสดงว่าคุณยอมรับข้อกำหนดของเรา',
    applicationError: 'ข้อผิดพลาดของแอปพลิเคชัน',
    somethingWentWrong: 'มีบางอย่างผิดพลาด',
    permissionDenied: 'คุณไม่มีสิทธิ์',
    reloadApplication: 'โหลดแอปพลิเคชันใหม่',
    mon: 'จ.',
    tue: 'อ.',
    wed: 'พ.',
    thu: 'พฤ.',
    fri: 'ศ.',
    sat: 'ส.',
    sun: 'อา.',
    w1: 'สัปดาห์ที่ 1',
    w2: 'สัปดาห์ที่ 2',
    w3: 'สัปดาห์ที่ 3',
    w4: 'สัปดาห์ที่ 4',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  t: (key: string) => string;
  formatCurrency: (amount: number) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as LanguageCode) || 'en';
  });

  const setLanguage = (code: LanguageCode) => {
    setLanguageState(code);
    localStorage.setItem('app_language', code);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  const formatCurrency = (amount: number): string => {
    const lang = languages.find(l => l.code === language) || languages[0];
    return new Intl.NumberFormat(lang.locale, {
      style: 'currency',
      currency: lang.currency,
    }).format(amount);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatCurrency }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
